<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Variant Calling – ISG 5312 - Genomic Data Analysis in Practice II</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02_3_filteringVariants.html" rel="next">
<link href="./02_1_qc.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02_0_variantDetection.html">Variant Detection and Genotyping</a></li><li class="breadcrumb-item"><a href="./02_2_variantCalling.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variant Calling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ISG 5312 - Genomic Data Analysis in Practice II</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_0_IntroToGit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Git</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_1_git-ingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First steps with Git</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_2_moreGit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">More Git</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02_0_variantDetection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variant Detection and Genotyping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_1_qc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variant calling - First Steps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_2_variantCalling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variant Calling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_3_filteringVariants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Filtering and Assessing Variants</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_4_assessingAnnotating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing and Annotating Variants</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_0_genomeAssembly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Genome Assembly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_1_genomeAssemblyKmers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Genome Assembly - first steps</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Single-cell RNAseq</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Pipeline development with Nextflow</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">4.1</span> Learning Objectives</a></li>
  <li><a href="#multi-sample-variant-calling" id="toc-multi-sample-variant-calling" class="nav-link" data-scroll-target="#multi-sample-variant-calling"><span class="header-section-number">4.2</span> Multi-sample variant calling</a></li>
  <li><a href="#freebayes" id="toc-freebayes" class="nav-link" data-scroll-target="#freebayes"><span class="header-section-number">4.3</span> <code>freebayes</code></a>
  <ul class="collapse">
  <li><a href="#freebayes-and-short-haplotypes" id="toc-freebayes-and-short-haplotypes" class="nav-link" data-scroll-target="#freebayes-and-short-haplotypes"><span class="header-section-number">4.3.1</span> freebayes and short haplotypes</a></li>
  <li><a href="#running-freebayes" id="toc-running-freebayes" class="nav-link" data-scroll-target="#running-freebayes"><span class="header-section-number">4.3.2</span> Running <code>freebayes</code></a></li>
  </ul></li>
  <li><a href="#bcftools" id="toc-bcftools" class="nav-link" data-scroll-target="#bcftools"><span class="header-section-number">4.4</span> <code>bcftools</code></a>
  <ul class="collapse">
  <li><a href="#running-bcftools" id="toc-running-bcftools" class="nav-link" data-scroll-target="#running-bcftools"><span class="header-section-number">4.4.1</span> Running <code>bcftools</code></a></li>
  <li><a href="#bcftools-options" id="toc-bcftools-options" class="nav-link" data-scroll-target="#bcftools-options"><span class="header-section-number">4.4.2</span> <code>bcftools</code> options</a></li>
  <li><a href="#resource-usage-1" id="toc-resource-usage-1" class="nav-link" data-scroll-target="#resource-usage-1"><span class="header-section-number">4.4.3</span> Resource usage</a></li>
  </ul></li>
  <li><a href="#parallelizing-variant-calling" id="toc-parallelizing-variant-calling" class="nav-link" data-scroll-target="#parallelizing-variant-calling"><span class="header-section-number">4.5</span> Parallelizing variant calling</a></li>
  <li><a href="#two-step-variant-calling-with-gatk" id="toc-two-step-variant-calling-with-gatk" class="nav-link" data-scroll-target="#two-step-variant-calling-with-gatk"><span class="header-section-number">4.6</span> Two-step variant calling with <code>gatk</code></a>
  <ul class="collapse">
  <li><a href="#running-the-workflow" id="toc-running-the-workflow" class="nav-link" data-scroll-target="#running-the-workflow"><span class="header-section-number">4.6.1</span> Running the workflow</a></li>
  <li><a href="#options-in-the-gatk-approach" id="toc-options-in-the-gatk-approach" class="nav-link" data-scroll-target="#options-in-the-gatk-approach"><span class="header-section-number">4.6.2</span> Options in the GATK approach</a></li>
  </ul></li>
  <li><a href="#what-about-aiml" id="toc-what-about-aiml" class="nav-link" data-scroll-target="#what-about-aiml"><span class="header-section-number">4.7</span> What about AI/ML!?!</a></li>
  <li><a href="#the-vcf-format" id="toc-the-vcf-format" class="nav-link" data-scroll-target="#the-vcf-format"><span class="header-section-number">4.8</span> The <strong>VCF</strong> format</a>
  <ul class="collapse">
  <li><a href="#the-header" id="toc-the-header" class="nav-link" data-scroll-target="#the-header"><span class="header-section-number">4.8.1</span> The header</a></li>
  <li><a href="#the-tabular-data" id="toc-the-tabular-data" class="nav-link" data-scroll-target="#the-tabular-data"><span class="header-section-number">4.8.2</span> The tabular data</a></li>
  <li><a href="#how-do-we-dig-in-to-a-vcf-file" id="toc-how-do-we-dig-in-to-a-vcf-file" class="nav-link" data-scroll-target="#how-do-we-dig-in-to-a-vcf-file"><span class="header-section-number">4.8.3</span> How do we dig in to a VCF file?</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">4.9</span> Conclusions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02_0_variantDetection.html">Variant Detection and Genotyping</a></li><li class="breadcrumb-item"><a href="./02_2_variantCalling.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variant Calling</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variant Calling</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">4.1</span> Learning Objectives</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Learning Objectives:</strong></td>
</tr>
<tr class="even">
<td>Identify variants and genotype samples against a reference genome.</td>
</tr>
<tr class="odd">
<td>Manipulate the VCF format.</td>
</tr>
</tbody>
</table>
<p>In this section we’re going to take our qc’ed and aligned data and call variants using a couple different methods. We’ll demonstrate <code>freebayes</code> and <code>bcftools</code>, which do multi-sample variant calling, and <code>GATK</code> which can do basic multi-sample variant calling, but we’ll walk through the step-wise procedure for calling variants on multiple samples because it’s a great way of doing variant calling when your set of samples could grow over time. We’ll also see a basic split-apply-combine approach to variant calling. We’ll also introduce the VCF format and some tools we can use to manipulate it.</p>
</section>
<section id="multi-sample-variant-calling" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="multi-sample-variant-calling"><span class="header-section-number">4.2</span> Multi-sample variant calling</h2>
<p>When you have more than one sample (typical when variant calling) you want to combine the samples together so they can be called simultaneously rather than calling variants on a per-sample basis and then combining them. This has a couple benefits:</p>
<ul>
<li><strong>Combining the data increases statistical power</strong>. When alleles are shared by more than one individual, pooling the data adds more evidence that they are real (rare alleles always remain a relative challenge).</li>
<li><strong>Calling variants across samples unifies representation of complex variants</strong>. Some variants have more than one possible representation and calling samples together ensures representation is consistent across samples. Representation issues arise most often with complex variants involving multiple indels or mixtures of SNPs and indels and/or when you have multiple haplotypes. If you called variants on each sample separately with the intent to combine them later, you could wind up with the same alleles being represented differently, which could be a hindrance.</li>
<li><strong>Homozygous reference genotypes (at variable sites) are accurately called</strong> The output of variant calling algorithms typically only outputs variant records at sites with <em>alternate alleles</em> (ones that differ from the reference genome) and does not distinguish sites with no data (or not enough evidence to make a call) from sites where there is good evidence for a genotype that is homozygous for the reference allele. If you do single sample calling and combine later, your site x genotype matrix will be splattered with missing data and you won’t really know if those missing genotypes are ref/ref genotypes or actually missing data and it won’t be safe to assume either way.</li>
</ul>
</section>
<section id="freebayes" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="freebayes"><span class="header-section-number">4.3</span> <code>freebayes</code></h2>
<p><a href="https://github.com/freebayes/freebayes"><code>Freebayes</code></a> is a popular variant caller. It uses a Bayesian model that accounts for many different features of the mapped data in trying to distinguish errors from true variation. It has a notably simple in application in that it does not require pre-processing or filters to be applied to the read data and produces output in a single step. As the authors note in the github readme, freebayes adheres to the Unix philosophy of creating modular tools that can read from stdin and write to stdout and be chained together by users into pipelines that fit their specific needs. This is a really nice feature that makes it easy to work with.</p>
<section id="freebayes-and-short-haplotypes" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="freebayes-and-short-haplotypes"><span class="header-section-number">4.3.1</span> freebayes and short haplotypes</h3>
<p>A major distinguishing feature of freebayes is that it outputs short haplotype variants. Working with haplotypes improves the sensitivity and specificity of variant calling, but as output, they can be useful or annoying, depending on your downstream application.</p>
<p>Consider the codon <code>TTT</code>, which codes for phenyalanine. Now imagine you have a reference sequence with a protein containing <code>TTT</code> at some position and you have sequenced a diploid sample that is heterozygous <code>TTT/TAA</code>. If your variant caller outputs short haplotypes, you will see the genotype <code>TT/AA</code> and easily recognize that one is the reference sequence and the other produces a premature stop codon. If, like most others, your variant caller outputs two heterozygous SNPs <code>T/A</code> and <code>T/A</code> and no phasing information, you will have no way of knowing (without going back to the data) if you have the haplotypes <code>TT/AA</code>, producing <code>phenylalanine/stop codon</code> or <code>TA/AT</code>, producing <code>leucine/tyrosine</code>. Note that this is a general problem when we lack phasing information.</p>
<p>An example where these haplotypes can be a headache is in population genetics, where you might wish to calculate a statistic like <code>pi</code>, the mean pairwise divergence between a collection of sequences (phase is unimportant here). The short haplotypes introduce complexity into the calculations that simple SNPs avoid. .</p>
<p>We will look more at haplotypes and how to manage them later in this chapter in the section on variant normalization.</p>
</section>
<section id="running-freebayes" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="running-freebayes"><span class="header-section-number">4.3.2</span> Running <code>freebayes</code></h3>
<p>After all that introduction, running <code>freebayes</code> is pretty simple. We will continue in the <a href="https://github.com/isg-certificate/variants">variants GitHub repository</a> assuming you have completed chapter 2. Go to the directory <code>scripts/05_variantCalling</code> and look at script <code>01_freebayes.sh</code>.</p>
<p>We’re going to provide <code>freebayes</code> with a list of bam files (a useful feature when you’ve got tons of samples), so we’ll create that first:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a list of bam files</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="va">${INDIR}</span>/<span class="pp">*</span>.bam <span class="op">&gt;</span><span class="va">${INDIR}</span>/bam_list.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Then we can run the program, using a variable <code>$GEN</code> to hold the genome location and clean up the command line:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set a variable for the reference genome location</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span>../../genome/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># run freebayes</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="ex">freebayes</span> <span class="dt">\</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>-f <span class="va">${GEN}</span> <span class="dt">\</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>--bam-list <span class="va">${INDIR}</span>/bam_list.txt <span class="kw">|</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="ex">bgzip</span> <span class="at">-c</span> <span class="op">&gt;</span><span class="va">${OUTDIR}</span>/freebayes.vcf.gz</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="ex">tabix</span> <span class="at">-p</span> vcf <span class="va">${OUTDIR}</span>/freebayes.vcf.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="bgzip-and-tabix" class="level4" data-number="4.3.2.1">
<h4 data-number="4.3.2.1" class="anchored" data-anchor-id="bgzip-and-tabix"><span class="header-section-number">4.3.2.1</span> bgzip and tabix</h4>
<p>By default freebayes will write results to the standard output in uncompressed format. We’re going to pipe that to <code>bgzip</code> to compress it and then index the compressed file with <code>tabix</code>. These are both part of the <a href="http://www.htslib.org"><code>htslib</code></a> project, which also includes <code>samtools</code> and <code>bcftools</code> (more on bcftools in a moment).</p>
<p><code>bgzip</code> is a variant of <code>gzip</code>: “block gzip”. It does a slightly modified gzip compression, but can still be read by <code>gzip</code>, <code>gunzip</code>, <code>zgrep</code> etc. The modification allows for easy indexing of position sorted tabular genomic data for fast access to data from any genomic region (just as with sorted, indexed bam files).</p>
<p>Once the file is bgzipped, we index with <code>tabix</code>. <code>tabix</code> can be used to index any bgzipped position sorted tabular file, and once indexed, retrieve data from the file. It has a few preset modes for BED, GFF, and VCF, but you can specify which columns contain the positional information so that any tabular format can be effectively indexed. Here we specify <code>-p vcf</code> because our output is in <code>VCF</code> format.</p>
</section>
<section id="a-few-other-freebayes-options" class="level4" data-number="4.3.2.2">
<h4 data-number="4.3.2.2" class="anchored" data-anchor-id="a-few-other-freebayes-options"><span class="header-section-number">4.3.2.2</span> A few other <code>freebayes</code> options</h4>
<p>It’s worth skimming the <a href="https://github.com/freebayes/freebayes">github readme</a> for freebayes. It has lots of information and isn’t hard to read. We’ll highlight a few more useful options here.</p>
<ul>
<li><em>Calling variants in a specific region</em>: You can limit freebayes to calling variants in a single genomic interval with the following flag <code>-r chr20:29400000-34400000</code>. It probably would have been wise to do that in our case, as we only really have usable data from that region (mismapped reads notwithstanding). You can also provide a BED file containing multiple target regions with <code>-t targets.bed</code>. We could have limited freebayes to calling variants only in windows within our coverage threshold this way. This would have sped things up a little, particularly as it would not have needed to churn through all the useless data in that region with 6000x coverage.</li>
<li><em>Specifying populations</em>: freebayes puts a <em>prior probability distribution</em> on genotype frequencies that assumes that all samples in a run are drawn from a single population. If this is incorrect (it often is) this prior may increase the error rate for genotype calls (most likely by favoring heterozygote calls too much). If you have high coverage (as we do in the test data) this probably doesn’t matter too much, as the data will overwhelm the prior, but if your coverage is on the low end, it can cause real problems (particularly for very low pass sequencing). You can specify which samples belong to which populations with <code>--populations FILE</code> (see docs for details). You can turn off this prior altogether with <code>-w</code>.</li>
<li><em>Specifying genetic diversity</em>: freebayes also puts a prior on the expected genetic diversity. By default this is <code>0.001</code>. This is appropriate for human data, but won’t be correct for everything. <em>Fundulus heteroclitus</em> populations range in diversity from <code>0.008</code> to <code>0.02</code>. Again, with high coverage data this prior will have less influence that with low. You can change it with <code>-T &lt;expected diversity&gt;</code>. You can turn off both this and the population prior with <code>-k</code>, a good idea if you have low coverage.</li>
<li><em>Specifying ploidy</em>: To set default ploidy, or to provide ploidy (or copy number) by region, and even by sample, look at the options <code>--ploidy</code> and <code>--cnv-map</code>.</li>
</ul>
</section>
<section id="resource-usage" class="level4" data-number="4.3.2.3">
<h4 data-number="4.3.2.3" class="anchored" data-anchor-id="resource-usage"><span class="header-section-number">4.3.2.3</span> Resource usage</h4>
<p><code>freebayes</code> is pretty lightweight. It can <em>only</em> use 1 cpu. The amount of memory required depends on the number of samples and the depth of coverage. For our 3 samples at ~50x coverage, we get the following <code>seff</code> output:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> seff 8846713</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> ID: 8846713</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="ex">Cluster:</span> xanadu</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="ex">User/Group:</span> nreid/cbc</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="ex">State:</span> COMPLETED <span class="er">(</span><span class="bu">exit</span> code 0<span class="kw">)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="ex">Nodes:</span> 1</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="ex">Cores</span> per node: 7</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Utilized: 01:03:01</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Efficiency: 14.30% of 07:20:32 core-walltime</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> Wall-clock time: 01:02:56</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Utilized: 718.59 MB</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Efficiency: 7.02% of 10.00 GB</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>For this run we considerably over-requested CPUs as we <em>can only use 1</em>. Memory is harder to predict and will increase with more samples. It took freebayes about an hour to process all of our data.</p>
</section>
</section>
</section>
<section id="bcftools" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="bcftools"><span class="header-section-number">4.4</span> <code>bcftools</code></h2>
<p><code>bcftools</code> is part of the <code>htslib</code> project mentioned above. It includes lots of tools for calling variants and for manipulating them downstream. Its variant calling pipeline is <em>much, much</em> faster than freebayes (or GATK, below), but it tends to produce slightly worse calls, mostly at loci where there is complex indel/snp variation. This comes down to the fact that it does not do haplotypic inference as freebayes does or local assembly as GATK does. Depending on your application, the speed and convenience gains may greatly outweigh the computational costs. It also has the benefit of being part of a large open-source project that is continuously developed and supported. Like freebayes, bcftools is very much developed around the Unix ethos of simple tools built for piping.</p>
<section id="running-bcftools" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="running-bcftools"><span class="header-section-number">4.4.1</span> Running <code>bcftools</code></h3>
<p>Calling variants with <code>bcftools</code> actually involves two steps. First, a summary of the read pileup across samples is generated. This digests the raw mapped BAM file into a tabular format that tracks potential alternate alleles and their evidence in each sample. That “pileup” file is then passed to a variant caller that evaluates the evidence and outputs variant calls and genotypes in VCF format.</p>
<p>Let’s have a look at the script <code>02_bcftools.sh</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a list of bam files</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="va">${INDIR}</span>/<span class="pp">*</span>.bam <span class="op">&gt;</span><span class="va">${INDIR}</span>/bam_list.txt</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># set reference genome location</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span>../../genome/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># call variants</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> mpileup <span class="at">-f</span> <span class="va">${GEN}</span> <span class="at">-b</span> <span class="va">${INDIR}</span>/bam_list.txt <span class="at">-q</span> 20 <span class="at">-Q</span> 30 <span class="kw">|</span> <span class="ex">bcftools</span> call <span class="at">-m</span> <span class="at">-v</span> <span class="at">-Oz</span> <span class="at">-o</span> <span class="va">${OUTDIR}</span>/bcftools.vcf.gz </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># index vcf</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="ex">tabix</span> <span class="at">-p</span> vcf <span class="va">${INDIR}</span>/bcftools.vcf.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>As above, we provide a list of bam files and the reference genome. We can do the full variant calling analysis by piping the two steps together <code>bcftools mpileup</code> which produces the summary of the evidence and <code>bcftools call</code>, which does the variant calling and genotyping.</p>
<p>In <code>mpileup</code> we have also provided input filters: <code>-q 20</code> ignores all bases with base quality &lt; 20 and <code>-Q 30</code> ignores all reads with mapping quality &lt; 30.</p>
<p>In <code>call</code> we provide some options: <code>-m</code> with uses the recommended “multi-allelic” caller, <code>-v</code> which outputs only variable sites, <code>-Oz</code> which outputs bgzip compressed variant calls and <code>-o ${OUTDIR}/bcftools.vcf.gz</code> to specify an output file name. We could also have let it write to stdout and redirected to a file (or piped the output to something else!).</p>
</section>
<section id="bcftools-options" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="bcftools-options"><span class="header-section-number">4.4.2</span> <code>bcftools</code> options</h3>
<p>We’ll keep this quick. <code>bcftools</code> has similar options to those mentioned above for freebayes. They can be found in the usage for <code>mpileup</code> and <code>call</code>. Note that there is no way to turn off the population priors, but you <em>can</em> provide a <code>--group-samples</code> file as with freebayes and put each sample in its own “population”.</p>
</section>
<section id="resource-usage-1" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="resource-usage-1"><span class="header-section-number">4.4.3</span> Resource usage</h3>
<p><code>bcftools</code> is very lightweight. It finished in 1/10th of the time that freebayes did and used 1/4 of the memory.</p>
<pre><code>Cores: 1
CPU Utilized: 00:06:17
CPU Efficiency: 99.74% of 00:06:18 core-walltime
Job Wall-clock time: 00:06:18
Memory Utilized: 164.06 MB
Memory Efficiency: 3.20% of 5.00 GB</code></pre>
</section>
</section>
<section id="parallelizing-variant-calling" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="parallelizing-variant-calling"><span class="header-section-number">4.5</span> Parallelizing variant calling</h2>
<p>We won’t do this here, but note that it is relatively straightforward to parallelize variant calling. The steps are:</p>
<ol type="1">
<li>Specify a set of windows within which to call variants.</li>
<li>Call variants in each window separately (perhaps using GNU <code>parallel</code> or an array job).</li>
<li>Combine the windowed variant calls, removing duplicate variants that overlap window edges.</li>
</ol>
<p><code>freebayes</code> distributes a script <code>freebayes_parallel</code>. You can find it here <code>/isg/shared/apps/freebayes/1.3.4/freebayes-1.3.4/scripts/freebayes-parallel</code> on Xanadu, or on <a href="https://github.com/freebayes/freebayes/blob/master/scripts/freebayes-parallel">github</a>.</p>
<p>It’s a simple bash script. The meat of it is:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="va">command</span><span class="op">=</span><span class="va">(</span><span class="st">"freebayes"</span> <span class="st">"</span><span class="va">$@</span><span class="st">"</span><span class="va">)</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="st">"</span><span class="va">$regionsfile</span><span class="st">"</span> <span class="kw">|</span> <span class="ex">parallel</span> <span class="at">-k</span> <span class="at">-j</span> <span class="st">"</span><span class="va">$ncpus</span><span class="st">"</span> <span class="st">"</span><span class="va">${command</span><span class="op">[@]</span><span class="va">}</span><span class="st">"</span> <span class="at">--region</span> {}</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="kw">)</span> <span class="kw">|</span> </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="ex">vcffirstheader</span> <span class="kw">|</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="ex">vcfstreamsort</span> <span class="at">-w</span> 1000 <span class="kw">|</span> </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="ex">vcfuniq</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>cat $regionsfile</code> pipes the genomic windows, however you define them, to <code>parallel</code>. The parallel option <code>-k</code> means process the input <em>in order</em> (and output it that way).<code>-j</code> gives a number of jobs to run simultaneously (one for each cpu in this case). Then you have the freebayes command line <code>"${command[@]}"</code> with <code>--region {}</code> appended to the end, so freebayes runs on just that region. All of this is wrapped in <code>()</code>, which typically groups commands into a single stdout stream. It’s not doing anything useful here, but it’s in the original script.</p>
<p>The output here is a single stream of VCF files</p>
<p>The next three commands process the output stream of variant calls. They are part of the <a href="https://github.com/vcflib/vcflib"><code>vcflib</code></a> suite. <code>vcffirstheader</code> retains the header from <em>just</em> the first VCF output (because these are parallel invocations of freebayes, each output VCF will have a header). <code>vcfstreamsort</code> sorts variants in a small window (1000 sites) to account for any weirdness due to duplicated variant calls at region edges. <code>vcfuniq</code> then removes any such duplicated variants.</p>
<p>This is handy for cases where the job can be usefully accelerated within a single node. Instead of using <code>parallel</code>, you could also break this out into an array job and spread the work over 100 (max number of jobs on Xanadu) simultaneous array tasks for the first step, and then in a second job combine the results.</p>
<p>If your independent project involves variant calling, you should really consider some version of this to speed things up. You can do it for any of the variant callers.</p>
</section>
<section id="two-step-variant-calling-with-gatk" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="two-step-variant-calling-with-gatk"><span class="header-section-number">4.6</span> Two-step variant calling with <code>gatk</code></h2>
<p>The last variant caller we’ll demonstrate is the <code>HaplotypeCaller</code> module from the package <a href="https://gatk.broadinstitute.org/hc/en-us"><code>GATK</code></a>.</p>
<p><code>GATK</code> is a very large suite of tools centered mostly on variant calling. It’s developed at <a href="https://www.broadinstitute.org">The Broad Institute</a>, a large biomedical research institute focused on genomics, and affiliated with Harvard and M.I.T. <code>GATK</code> is one of the most widely used packages for variant calling and performs very well in tests. It has extensive documentation, and has published “best-practice” recommendations for how to use their software. Unfortunately, the best practices are often very complex <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, and sometimes require resources that are unavailable in model systems (e.g.&nbsp;“gold-standard” variant call sets). In recent years the documentation has become out of date and hard to parse, with lots of broken links.</p>
<p>While <code>HaplotypeCaller</code> can be run in one step just like <code>freebayes</code>, a cool feature of GATK is its ability to do stepwise joint calling of multiple samples. The advantage of this procedure arises mainly if you have a study where you are likely going to have sampling that increases over time. In this procedure, the heaviest computation is done first, and can be done independently for each sample. If you save the products of that computation, then when you get new samples, you only need to do the initial step for the new samples before combining all samples together. This can save lots of time over standard joint calling in which all the computation needs to be redone every time a new sample is obtained.</p>
<section id="running-the-workflow" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="running-the-workflow"><span class="header-section-number">4.6.1</span> Running the workflow</h3>
<p>There are three key steps:</p>
<ol type="1">
<li>Run <code>HaplotypeCaller</code> in GVCF mode on each sample. A <code>GVCF</code> is a modification of <code>VCF</code> format (which we haven’t covered yet). This is the heavy compute. It can be parallelized across samples and genomic regions if necessary.</li>
<li>Run <code>GenomicsDBImport</code> to create a database of your samples (this runs quickly).</li>
<li>Run <code>GenotypeGVCFs</code> to create joint genotype calls (this also runs quickly).</li>
</ol>
<p>Let’s look at the scripts.</p>
<section id="creating-the-sequence-dictionary" class="level4" data-number="4.6.1.1">
<h4 data-number="4.6.1.1" class="anchored" data-anchor-id="creating-the-sequence-dictionary"><span class="header-section-number">4.6.1.1</span> Creating the sequence dictionary</h4>
<p>We need one helper file that we don’t already have, a sequence dictionary for the reference genome. We’re going to run <code>03_createDict.sh</code> to create that. It uses <a href="https://broadinstitute.github.io/picard/"><code>Picard</code></a>, a toolkit for manipulating genomes, alignment files, and variant calls.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load required software</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load picard/2.23.9</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># input/output</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="va">INDIR</span><span class="op">=</span>../../results/03_Alignment/bwa_align/</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_variantCalling/gatk</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">$OUTDIR</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># set a variable for the reference genome location</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span>../../genome/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># create required .dict file</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="ex">java</span> <span class="at">-jar</span> <span class="va">$PICARD</span> CreateSequenceDictionary R=<span class="va">$GEN</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We have seen Java programs run this way before, but let’s reinforce what’s happening. When we load the module, an environment variable is created that points at a java “jar” file.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> module load picard/2.23.9</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> echo <span class="va">$PICARD</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="ex">/isg/shared/apps/picard/2.23.9/picard.jar</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We start the program with <code>java -jar $PICARD</code>. We can modify the memory usage using command line options as we’ll see in a later script.</p>
</section>
<section id="generating-the-gvcf-files" class="level4" data-number="4.6.1.2">
<h4 data-number="4.6.1.2" class="anchored" data-anchor-id="generating-the-gvcf-files"><span class="header-section-number">4.6.1.2</span> Generating the GVCF files</h4>
<p>In our next step, we’ll generate one GVCF file for each sample, using an array job. Look at the script <code>04_makeGVCFs.sh</code></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="va">SAMPLELIST</span><span class="op">=</span><span class="va">(</span>son dad mom<span class="va">)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="va">SAMPLE</span><span class="op">=</span><span class="va">${SAMPLELIST</span><span class="op">[</span><span class="va">$SLURM_ARRAY_TASK_ID</span><span class="op">]</span><span class="va">}</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># set a variable for the reference genome location</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span>../../genome/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># run haplotype caller on one sample</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="ex">gatk</span> HaplotypeCaller <span class="dt">\</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">-R</span> <span class="va">${GEN}</span> <span class="dt">\</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">-I</span> <span class="va">${INDIR}</span>/<span class="va">${SAMPLE}</span>.bam <span class="dt">\</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">-ERC</span> GVCF <span class="dt">\</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">--output</span> <span class="va">${OUTDIR}</span>/<span class="va">${SAMPLE}</span>.g.vcf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The flag <code>-ERC GVCF</code> directs GATK to produce the GVCF file. <code>ERC</code> stands for “emit reference confidence”. So these files are actually tracking whether or not there is good evidence for a homozygous reference genotype in the sample.</p>
<p>After we’ve run this we should see this in the results directory:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> ll ../../results/05_variantCalling/gatk/</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="ex">-rw-r--r--</span> 1 nreid cbc  29M Feb  5 16:50 dad.g.vcf</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="ex">-rw-r--r--</span> 1 nreid cbc  91K Feb  5 16:50 dad.g.vcf.idx</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="ex">-rw-r--r--</span> 1 nreid cbc  26M Feb  5 16:51 mom.g.vcf</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="ex">-rw-r--r--</span> 1 nreid cbc  82K Feb  5 16:51 mom.g.vcf.idx</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="ex">-rw-r--r--</span> 1 nreid cbc  25M Feb  5 16:55 son.g.vcf</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="ex">-rw-r--r--</span> 1 nreid cbc  80K Feb  5 16:55 son.g.vcf.idx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This step uses the most resources. For one of the three array tasks:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> seff 8847173_0</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> ID: 8847174</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Array</span> Job ID: 8847173_0</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="ex">Cluster:</span> xanadu</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="ex">User/Group:</span> nreid/cbc</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="ex">State:</span> COMPLETED <span class="er">(</span><span class="bu">exit</span> code 0<span class="kw">)</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="ex">Nodes:</span> 1</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="ex">Cores</span> per node: 7</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Utilized: 02:05:44</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Efficiency: 23.89% of 08:46:17 core-walltime</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> Wall-clock time: 01:15:11</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Utilized: 13.30 GB</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Efficiency: 66.51% of 20.00 GB</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>So in fact we used something like 3hrs 45min of wall time to run these three tasks. This probably would have been a bit faster if we had specified that it should only run on our focal 5mb region instead of crawling across the whole genome. In any case, it took more resources that freebayes and <em>vastly</em> more resources than bcftools.</p>
</section>
<section id="creating-the-database" class="level4" data-number="4.6.1.3">
<h4 data-number="4.6.1.3" class="anchored" data-anchor-id="creating-the-database"><span class="header-section-number">4.6.1.3</span> Creating the database</h4>
<p>In the next step we’re going to create our database. This step can be done on <em>at most</em> one reference sequence at a time. So you <em>must</em> specify a region (in this case all of chr20) when you do this step, and you <em>must</em> do this step once for each sequence in your reference genome. So in some sense GATK encourages parallelism at this stage, though this step and the next are quick enough that it doesn’t seem to that important in practice. Have a look at the script <code>05_DBimport.sh</code>.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make an "arguments" file to provide all samples</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">find</span> <span class="va">${INDIR}</span> <span class="at">-name</span> <span class="st">"*g.vcf"</span> <span class="op">&gt;</span><span class="va">${INDIR}</span>/args.txt</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="at">-i</span> <span class="st">'s/^/-V /'</span> <span class="va">${INDIR}</span>/args.txt</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#IMPORTANT: The -Xmx value the tool is run with should be less than the total amount of physical memory available by at least a few GB, as the native TileDB library requires additional memory on top of the Java memory. Failure to leave enough memory for the native code can result in confusing error messages!</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="ex">gatk</span> <span class="at">--java-options</span> <span class="st">"-Xmx10g -Xms4g"</span> GenomicsDBImport <span class="dt">\</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">--genomicsdb-workspace-path</span> <span class="va">${OUTDIR}</span> <span class="dt">\</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">--overwrite-existing-genomicsdb-workspace</span> true <span class="dt">\</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">-L</span> chr20 <span class="dt">\</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">--arguments_file</span> <span class="va">${INDIR}</span>/args.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We need to tell it which samples to use. You can specify them on the command line with <code>-V sample1.g.vcf</code>, but that gets tedious. So we’re going to provide a file with a list of arguments to append to the command line “args.txt”. It contains a <code>-V</code> flag for each GVCF file.</p>
<p>When we run <code>GenomicsDBImport</code> we specify some java options: <code>--java-options "-Xmx10g -Xms4g"</code>. Those give the maximum and minimum memory boundaries for this execution of the program. See the comment line saying we need to request <em>more</em> memory than the java option max from SLURM.</p>
<p>In this case we’re providing a workspace path, but also telling the program to overwrite any existing data there (helpful when you’re testing the code out and running it over and over again).</p>
<p>When we finally run this, it goes quickly, taking only 13 minutes:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> seff 8847371</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> ID: 8847371</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Cluster:</span> xanadu</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="ex">User/Group:</span> nreid/cbc</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="ex">State:</span> COMPLETED <span class="er">(</span><span class="bu">exit</span> code 0<span class="kw">)</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="ex">Nodes:</span> 1</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="ex">Cores</span> per node: 7</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Utilized: 00:00:57</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Efficiency: 7.14% of 00:13:18 core-walltime</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> Wall-clock time: 00:01:54</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Utilized: 2.08 GB</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Efficiency: 13.86% of 15.00 GB</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="generating-the-vcf-file" class="level4" data-number="4.6.1.4">
<h4 data-number="4.6.1.4" class="anchored" data-anchor-id="generating-the-vcf-file"><span class="header-section-number">4.6.1.4</span> Generating the VCF file</h4>
<p>Finally we can run the script that actually generates our VCF output, <code>06_genotypeGVCFs.sh</code>. Let’s have a look at it:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set a variable for the reference genome location</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span>../../genome/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="ex">gatk</span> GenotypeGVCFs <span class="dt">\</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">-R</span> <span class="va">${GEN}</span> <span class="dt">\</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">-V</span> gendb://../../results/05_variantCalling/gatk/db <span class="dt">\</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">-O</span> <span class="va">${OUTDIR}</span>/gatk.vcf </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="ex">bgzip</span> <span class="va">${OUTDIR}</span>/gatk.vcf </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="ex">tabix</span> <span class="at">-p</span> vcf <span class="va">${OUTDIR}</span>/gatk.vcf.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>At this point it’s very straightforward. Provide the reference genome, the location of the database and an output file name. Because the database is already region-restricted, we don’t need to specify a region.</p>
<p>After we output the VCF file, we bgzip it and tabix index it.</p>
<p>Again, this step does not require much in the way of resources. It took less than 1 minute to process chr20.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> seff 8847490</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> ID: 8847490</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Cluster:</span> xanadu</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="ex">User/Group:</span> nreid/cbc</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="ex">State:</span> COMPLETED <span class="er">(</span><span class="bu">exit</span> code 0<span class="kw">)</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="ex">Nodes:</span> 1</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="ex">Cores</span> per node: 7</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Utilized: 00:00:49</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="ex">CPU</span> Efficiency: 15.91% of 00:05:08 core-walltime</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="ex">Job</span> Wall-clock time: 00:00:44</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Utilized: 1.13 GB</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="ex">Memory</span> Efficiency: 7.51% of 15.00 GB</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="options-in-the-gatk-approach" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="options-in-the-gatk-approach"><span class="header-section-number">4.6.2</span> Options in the GATK approach</h3>
<p>It is possible to split up the GVCF calling into subregions to speed it up, though it gets a little complex parallelizing across individuals and regions, requiring some work to organize.</p>
<p>GATK also uses a population prior, but we don’t know how to turn it off or specify population groupings! You <em>can</em> change the expected genetic diversity, however, which by default is again set at 0.001 (this value is ubiquitous because it is approximately the value in humans).</p>
</section>
</section>
<section id="what-about-aiml" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="what-about-aiml"><span class="header-section-number">4.7</span> What about AI/ML!?!</h2>
<p>There is another big variant caller we are <em>not</em> covering in this course, but it is a pretty cool one: Google’s <a href="https://github.com/google/deepvariant"><code>DeepVariant</code></a>.</p>
<p><code>DeepVariant</code> uses machine learning rather than a probabilistic model to distinguish sequencing and mapping errors from true variation and genotype samples. In tests, it works well. The trick is that ML models like those used in DeepVariant need to be <em>trained</em> on a set of true variants. Ideally those true variants need to share similar characteristics with those in the data that will ultimately be analyzed.</p>
<p>In model systems (human, mouse, <em>Drosophila</em>) there are often resources available to train models, and the trained models may already be available (the one distributed with DeepVariant is trained on human data). Training is not computationally trivial and relies heavily on the quality of the input.</p>
<p>In non-model systems, good training data may not be available, or you may not have the time or expertise to do your own training. So the question becomes, will a variant detection model trained on another species do well on mine? The answer to that is… maybe, or maybe not. It really depends on what features of the data the model has learned to associate with true variants and artifacts, and whether those are consistent with your species. For genetically diverse species, such as <em>Fundulus heteroclitus</em>, it’s highly likely that DeepVariant would do very poorly when applying a human-trained model. In humans, tight clusters of variants often signal false positives. In killifish, there is so much genetic diversity that <em>all</em> variants will look crowded together by comparison. This could conceivably cause problems.</p>
<p>See this <a href="https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/">blog post</a> from google about this very question, suggesting that a human trained model didn’t do so well when run on mosquitoes, but species-specific training greatly improved the situation.</p>
</section>
<section id="the-vcf-format" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="the-vcf-format"><span class="header-section-number">4.8</span> The <strong>VCF</strong> format</h2>
<p>Ok, we’ve finally gotten our VCF files. Let’s go over what a VCF file actually is. VCF (or <strong>V</strong>ariant <strong>C</strong>all <strong>F</strong>ormat) is the dominant file format used to store variant calls generated from high-throughput sequencing data. VCF format is a bit of a bear because it packs in so much information. After we cover it here, we’ll look at tools for extracting useful information from it.</p>
<p>At this point, the format will probably seem a <em>little</em> familiar, as it is a tabular file that begins with a (sometimes) extensive header. It even has one field (INFO) that serves as a garbage bin of semi-colon separated tags (just like the attributes field in GTF/GFF!).</p>
<p>You can find a formal specification <a href="https://samtools.github.io/hts-specs/VCFv4.2.pdf">here</a>. But we’ll also cover the basics in this section.</p>
<p>We’re going to use <code>bcftools</code> to extract bits of the VCF to view them. We saw above how we can use it for variant calling, but it’s got <em>tons</em> of other functionality (much like <code>samtools</code>!) so it’s worth skimming through <a href="https://samtools.github.io/bcftools/bcftools.html">the documentation</a> to see what it can do beyond what you see here.</p>
<p>We’re going to look at the freebayes VCF because it produces the most annotations for each variant.</p>
<section id="the-header" class="level3" data-number="4.8.1">
<h3 data-number="4.8.1" class="anchored" data-anchor-id="the-header"><span class="header-section-number">4.8.1</span> The header</h3>
<p>VCF begins with a header. <code>bcftools view</code> prints a compressed VCF file to stdout, and <code>-h</code> prints <em>only</em> the header.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-h</span> variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">head</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##fileformat=VCFv4.2
##FILTER=&lt;ID=PASS,Description="All filters passed"&gt;
##fileDate=20250205
##source=freeBayes v1.3.4
##reference=../../genome/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta
##contig=&lt;ID=chr1,length=248956422&gt;
##contig=&lt;ID=chr2,length=242193529&gt;
##contig=&lt;ID=chr3,length=198295559&gt;
##contig=&lt;ID=chr4,length=190214555&gt;
##contig=&lt;ID=chr5,length=181538259&gt;</code></pre>
</div>
</div>
<p>The biggest part of the header is a sequence dictionary, listing all reference sequences and their lengths.</p>
<p>Let’s look at the last few lines of the header:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-h</span> variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">tail</span> <span class="at">-n</span> 20 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##INFO=&lt;ID=LEN,Number=A,Type=Integer,Description="allele length"&gt;
##INFO=&lt;ID=MQM,Number=A,Type=Float,Description="Mean mapping quality of observed alternate alleles"&gt;
##INFO=&lt;ID=MQMR,Number=1,Type=Float,Description="Mean mapping quality of observed reference alleles"&gt;
##INFO=&lt;ID=PAIRED,Number=A,Type=Float,Description="Proportion of observed alternate alleles which are supported by properly paired read fragments"&gt;
##INFO=&lt;ID=PAIREDR,Number=1,Type=Float,Description="Proportion of observed reference alleles which are supported by properly paired read fragments"&gt;
##INFO=&lt;ID=MIN_DP,Number=1,Type=Integer,Description="Minimum depth in gVCF output block."&gt;
##INFO=&lt;ID=END,Number=1,Type=Integer,Description="Last position (inclusive) in gVCF output record."&gt;
##FORMAT=&lt;ID=GT,Number=1,Type=String,Description="Genotype"&gt;
##FORMAT=&lt;ID=GQ,Number=1,Type=Float,Description="Genotype Quality, the Phred-scaled marginal (or unconditional) probability of the called genotype"&gt;
##FORMAT=&lt;ID=GL,Number=G,Type=Float,Description="Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy"&gt;
##FORMAT=&lt;ID=DP,Number=1,Type=Integer,Description="Read Depth"&gt;
##FORMAT=&lt;ID=AD,Number=R,Type=Integer,Description="Number of observation for each allele"&gt;
##FORMAT=&lt;ID=RO,Number=1,Type=Integer,Description="Reference allele observation count"&gt;
##FORMAT=&lt;ID=QR,Number=1,Type=Integer,Description="Sum of quality of the reference observations"&gt;
##FORMAT=&lt;ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count"&gt;
##FORMAT=&lt;ID=QA,Number=A,Type=Integer,Description="Sum of quality of the alternate observations"&gt;
##FORMAT=&lt;ID=MIN_DP,Number=1,Type=Integer,Description="Minimum depth in gVCF output block."&gt;
##bcftools_viewVersion=1.21+htslib-1.21
##bcftools_viewCommand=view -h variants/results/05_variantCalling/freebayes/freebayes.vcf.gz; Date=Sat Feb 22 15:39:17 2025
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  son dad mom</code></pre>
</div>
</div>
<p>They record how we produced the VCF we’re viewing now (unfortunately freebayes did not add its command line call to the header).</p>
<p>Note lines beginning: <code>INFO=&lt;ID=...</code> and <code>FORMAT=&lt;ID=...</code>. These give the definitions of tags found in the INFO and FORMAT fields of the tabular data. If you want to find out what the tag <code>DP</code> means, for example, you can do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-h</span> variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">grep</span> <span class="st">"=DP,"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##INFO=&lt;ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus"&gt;
##FORMAT=&lt;ID=DP,Number=1,Type=Integer,Description="Read Depth"&gt;</code></pre>
</div>
</div>
<p>The final line is the header line for the tabular data that follows. The fields are:</p>
<ol type="1">
<li><strong>CHROM</strong>: The reference sequence of the variant record, e.g.&nbsp;<code>chr20</code> or possibly an NCBI accession.</li>
<li><strong>POS</strong>: The left most position of the variant. In case of an insertion, will be the base to the left of an insertion. 1-indexed (not zero).</li>
<li><strong>ID</strong>: Any database identifiers that have been attached to the variant (such as <a href="https://www.ncbi.nlm.nih.gov/snp/">dbSNP</a> IDs. see next chapter). Empty by default.</li>
<li><strong>REF</strong>: The reference allele. Cannot be empty, as in the case of an insertion. Will be th base to the left.</li>
<li><strong>ALT</strong>: One or more alternate alleles. Comma-separated. Cannot be empty. In case of a deletion will be the base to the left of the deletion.</li>
<li><strong>QUAL</strong>: Phred-scaled variant quality determined by variant caller. You should know what these are by now!</li>
<li><strong>FILTER</strong>: Can be populated with values like <code>PASS</code> or <code>FAIL</code> or <code>LowQual</code> to indicate variants that pass some filtering procedure. Usually empty by default.</li>
<li><strong>INFO</strong>: A semicolon separated list of annotations of the variant. Almost always contains basic information like the total depth at the locus, the counts of each observed allele and some other useful stuff. We’ll see how to extract it into an easier format later.</li>
<li><strong>FORMAT</strong>: Gives the format of the following fields, which contain genotypes.</li>
<li><strong>genotypes for sample X</strong>: Every field from 10 onward contains genotype information for a sample along with (typically) some annotations, as defined in the FORMAT field.</li>
</ol>
<p>Each column from 10 onwards represents one sample’s vector of genotypes.</p>
</section>
<section id="the-tabular-data" class="level3" data-number="4.8.2">
<h3 data-number="4.8.2" class="anchored" data-anchor-id="the-tabular-data"><span class="header-section-number">4.8.2</span> The tabular data</h3>
<p>Now let’s look at the tabular data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:33100000-33200000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">head</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>chr20   33100435    .   T   C   7253.87 .   AB=0;ABP=0;AC=6;AF=1;AN=6;AO=218;CIGAR=1X;DP=218;DPB=218;DPRA=0;EPP=3.6478;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=3;NUMALT=1;ODDS=91.0153;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=8104;QR=0;RO=0;RPL=116;RPP=4.96263;RPPR=0;RPR=102;RUN=1;SAF=119;SAP=6.99465;SAR=99;SRF=0;SRP=0;SRR=0;TYPE=snp    GT:DP:AD:RO:QR:AO:QA:GL 1/1:73:0,73:0:0:73:2712:-244.24,-21.9752,0  1/1:80:0,80:0:0:80:2938:-264.561,-24.0824,0 1/1:65:0,65:0:0:65:2454:-221.045,-19.567,0
chr20   33100454    .   C   T   7306.07 .   AB=0;ABP=0;AC=6;AF=1;AN=6;AO=219;CIGAR=1X;DP=219;DPB=219;DPRA=0;EPP=3.49615;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=3;NUMALT=1;ODDS=87.0387;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=8160;QR=0;RO=0;RPL=108;RPP=3.09954;RPPR=0;RPR=111;RUN=1;SAF=120;SAP=7.38299;SAR=99;SRF=0;SRP=0;SRR=0;TYPE=snp   GT:DP:AD:RO:QR:AO:QA:GL 1/1:76:0,76:0:0:76:2851:-256.745,-22.8783,0 1/1:84:0,84:0:0:84:3111:-280.139,-25.2865,0 1/1:59:0,59:0:0:59:2198:-198.023,-17.7608,0
chr20   33100524    .   C   T   7087.29 .   AB=0;ABP=0;AC=6;AF=1;AN=6;AO=222;CIGAR=1X;DP=222;DPB=222;DPRA=0;EPP=3.04943;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=3;NUMALT=1;ODDS=84.1199;PAIRED=0.995495;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=7917;QR=0;RO=0;RPL=102;RPP=6.17948;RPPR=0;RPR=120;RUN=1;SAF=118;SAP=4.92746;SAR=104;SRF=0;SRP=0;SRR=0;TYPE=snp   GT:DP:AD:RO:QR:AO:QA:GL 1/1:80:0,80:0:0:80:3005:-270.607,-24.0824,0 1/1:88:0,88:0:0:88:3005:-270.594,-26.4906,0 1/1:54:0,54:0:0:54:1907:-171.854,-16.2556,0
chr20   33100922    .   TCCAT   TCAT    6892.35 .   AB=0;ABP=0;AC=6;AF=1;AN=6;AO=225;CIGAR=1M1D3M;DP=226;DPB=180.8;DPRA=0;EPP=6.49431;EPPR=0;GTI=0;LEN=1;MEANALT=1.33333;MQM=59.7733;MQMR=0;NS=3;NUMALT=1;ODDS=89.5189;PAIRED=0.986667;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=7707;QR=0;RO=0;RPL=108;RPP=3.79203;RPPR=0;RPR=117;RUN=1;SAF=124;SAP=8.11567;SAR=101;SRF=0;SRP=0;SRR=0;TYPE=del  GT:DP:AD:RO:QR:AO:QA:GL 1/1:96:0,95:0:0:95:3234:-291.03,-28.5979,0  1/1:61:0,61:0:0:61:2117:-190.736,-18.3628,0 1/1:69:0,69:0:0:69:2356:-212.226,-20.7711,0
chr20   33101062    .   G   C   6054.04 .   AB=0.515152;ABP=3.1419;AC=5;AF=0.833333;AN=6;AO=195;CIGAR=1X;DP=228;DPB=228;DPRA=0;EPP=12.3755;EPPR=8.34028;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=69.7788;PAIRED=1;PAIREDR=0.969697;PAO=0;PQA=0;PQR=0;PRO=0;QA=7079;QR=1205;RO=33;RPL=115;RPP=16.6516;RPPR=8.34028;RPR=80;RUN=1;SAF=94;SAP=3.55595;SAR=101;SRF=21;SRP=8.34028;SRR=12;TYPE=snp GT:DP:AD:RO:QR:AO:QA:GL 1/1:87:0,87:0:0:87:3248:-292.458,-26.1896,0 0/1:66:32,34:32:1184:34:1175:-86.148,0,-86.9768 1/1:75:1,74:1:21:74:2656:-237.119,-20.4773,0
chr20   33101256    .   C   T   1054.39 .   AB=0.58209;ABP=6.93191;AC=1;AF=0.166667;AN=6;AO=39;CIGAR=1X;DP=220;DPB=220;DPRA=0.875817;EPP=5.73856;EPPR=5.37479;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=63.486;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1470;QR=6671;RO=180;RPL=21;RPP=3.51141;RPPR=4.21667;RPR=18;RUN=1;SAF=21;SAP=3.51141;SAR=18;SRF=88;SRP=3.20332;SRR=92;TYPE=snp    GT:DP:AD:RO:QR:AO:QA:GL 0/0:84:83,0:83:3020:0:0:0,-24.9855,-271.782 0/0:69:69,0:69:2583:0:0:0,-20.7711,-232.64  0/1:67:28,39:28:1068:39:1470:-112.389,0,-76.2508
chr20   33101562    .   CTTTTCTTTTGA    CTTCTTTTGA  529.868 .   AB=0.40678;ABP=7.46366;AC=1;AF=0.166667;AN=6;AO=24;CIGAR=1M2D9M;DP=225;DPB=221;DPRA=0.710843;EPP=3.37221;EPPR=4.11819;GTI=0;LEN=2;MEANALT=2;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=81.6124;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=875;QR=7339;RO=196;RPL=10;RPP=4.45795;RPPR=26.4533;RPR=14;RUN=1;SAF=17;SAP=12.0581;SAR=7;SRF=128;SRP=42.8945;SRR=68;TYPE=del    GT:DP:AD:RO:QR:AO:QA:GL 0/0:76:75,0:75:2831:0:0:0,-22.5772,-254.814 0/1:59:34,24:34:1257:24:875:-61.466,0,-95.8355  0/0:90:87,0:87:3251:0:0:0,-26.1896,-292.616
chr20   33101824    .   G   A   725.819 .   AB=0.461538;ABP=3.84548;AC=1;AF=0.166667;AN=6;AO=30;CIGAR=1X;DP=219;DPB=219;DPRA=0.844156;EPP=26.4622;EPPR=3.42611;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=67.3506;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1156;QR=7082;RO=188;RPL=20;RPP=10.2485;RPPR=3.0103;RPR=10;RUN=1;SAF=6;SAP=26.4622;SAR=24;SRF=69;SRP=31.8863;SRR=119;TYPE=snp   GT:DP:AD:RO:QR:AO:QA:GL 0/0:91:90,0:90:3378:0:0:0,-27.0927,-304.011 0/0:63:63,0:63:2374:0:0:0,-18.9649,-213.856 0/1:65:35,30:35:1330:30:1156:-84.7577,0,-100.405
chr20   33102044    .   T   G   0   .   AB=0;ABP=0;AC=0;AF=0;AN=6;AO=4;CIGAR=1X;DP=193;DPB=193;DPRA=0.919118;EPP=11.6962;EPPR=4.97275;GTI=0;LEN=1;MEANALT=1.5;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=61.3932;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=72;QR=6826;RO=187;RPL=0;RPP=11.6962;RPPR=7.20229;RPR=4;RUN=1;SAF=0;SAP=11.6962;SAR=4;SRF=101;SRP=5.62303;SRR=86;TYPE=snp  GT:DP:AD:RO:QR:AO:QA:GL 0/0:72:71,1:71:2576:1:13:0,-20.3742,-230.715    0/0:53:48,3:48:1794:3:59:0,-10.1644,-156.119    0/0:68:68,0:68:2456:0:0:0,-20.47,-221.219
chr20   33102134    .   T   C,G 7.50367e-15 .   AB=0,0;ABP=0,0;AC=0,0;AF=0,0;AN=6;AO=2,3;CIGAR=1X,1X;DP=171;DPB=171;DPRA=0.571429,0.655405;EPP=7.35324,9.52472;EPPR=4.31842;GTI=0;LEN=1,1;MEANALT=2,1.5;MQM=60,60;MQMR=60;NS=3;NUMALT=2;ODDS=46.6774;PAIRED=1,1;PAIREDR=1;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=55,37;QR=5947;RO=166;RPL=1,0;RPP=3.0103,9.52472;RPPR=4.31842;RPR=1,3;RUN=1,1;SAF=1,0;SAP=3.0103,9.52472;SAR=1,3;SRF=86;SRP=3.48122;SRR=80;TYPE=snp,snp GT:DP:AD:RO:QR:AO:QA:GL 0/0:74:74,0,0:74:2603:0,0:0,0:0,-22.2762,-234.443,-22.2762,-234.443,-234.443    0/0:38:34,2,2:34:1226:2,2:55,25:0,-5.81527,-105.463,-8.66201,-104.431,-108.169  0/0:59:58,0,1:58:2118:0,1:0,12:0,-17.4597,-190.705,-16.5608,-189.93,-189.629</code></pre>
</div>
</div>
<p>In this case we specify <code>-H</code> to <em>suppress</em> the header and <code>-r chr20:33100000-33200000</code> to identify a particular region.</p>
<p>We can see there’s a <em>lot</em> of information there. Let’s take it a bit at a time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:33100000-33200000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">head</span> <span class="kw">|</span> <span class="fu">cut</span> <span class="at">-f</span> 1-7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>chr20   33100435    .   T   C   7253.87 .
chr20   33100454    .   C   T   7306.07 .
chr20   33100524    .   C   T   7087.29 .
chr20   33100922    .   TCCAT   TCAT    6892.35 .
chr20   33101062    .   G   C   6054.04 .
chr20   33101256    .   C   T   1054.39 .
chr20   33101562    .   CTTTTCTTTTGA    CTTCTTTTGA  529.868 .
chr20   33101824    .   G   A   725.819 .
chr20   33102044    .   T   G   0   .
chr20   33102134    .   T   C,G 7.50367e-15 .</code></pre>
</div>
</div>
<p>Much cleaner! We can see a diversity of variant calls here. We have 7 biallelic SNPs, one multi-allelic SNP and two longer variants. The last two variants have <em>very bad</em> quality scores (0 and 7.50367e-15) respectively. Those are an example of freebayes opting for extreme high sensitivity, and we will definitely filter those out later. The other variant calls have rather extreme high quality scores. Improbably high, really. The probability of error for QUAL=7253.87 is 10<sup>-725</sup>. Take a moment to ask yourself whether we should ever believe any statistical output with that degree of confidence.</p>
<p>Anyway… these high quality variants are most likely real. The SNPs are straightforward. The haplotypes represent deletions, but they don’t seem to be represented in a very parsimonious way. The first one might better have the alleles TC and T indicating a single-base deletion. We’ll see how we can standardize representation later, but we can in fact see that’s exactly how GATK does it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:33100000-33200000 variants/results/05_variantCalling/gatk/gatk.vcf.gz <span class="kw">|</span> <span class="fu">head</span> <span class="kw">|</span> <span class="fu">cut</span> <span class="at">-f</span> 1-7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>chr20   33100435    .   T   C   8075.9  .
chr20   33100454    .   C   T   8110.9  .
chr20   33100524    .   C   T   7343.9  .
chr20   33100922    .   TC  T   8409.86 .
chr20   33101062    .   G   C   6336.13 .
chr20   33101256    .   C   T   1110.13 .
chr20   33101562    .   CTT C   935.09  .
chr20   33101824    .   G   A   997.13  .
chr20   33102548    .   G   A   4207.13 .
chr20   33103215    .   G   A   856.13  .</code></pre>
</div>
</div>
<p>Now let’s look at the INFO field:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:33100000-33200000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">head</span> <span class="kw">|</span> <span class="fu">cut</span> <span class="at">-f</span> 8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AB=0;ABP=0;AC=6;AF=1;AN=6;AO=218;CIGAR=1X;DP=218;DPB=218;DPRA=0;EPP=3.6478;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=3;NUMALT=1;ODDS=91.0153;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=8104;QR=0;RO=0;RPL=116;RPP=4.96263;RPPR=0;RPR=102;RUN=1;SAF=119;SAP=6.99465;SAR=99;SRF=0;SRP=0;SRR=0;TYPE=snp
AB=0;ABP=0;AC=6;AF=1;AN=6;AO=219;CIGAR=1X;DP=219;DPB=219;DPRA=0;EPP=3.49615;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=3;NUMALT=1;ODDS=87.0387;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=8160;QR=0;RO=0;RPL=108;RPP=3.09954;RPPR=0;RPR=111;RUN=1;SAF=120;SAP=7.38299;SAR=99;SRF=0;SRP=0;SRR=0;TYPE=snp
AB=0;ABP=0;AC=6;AF=1;AN=6;AO=222;CIGAR=1X;DP=222;DPB=222;DPRA=0;EPP=3.04943;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=3;NUMALT=1;ODDS=84.1199;PAIRED=0.995495;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=7917;QR=0;RO=0;RPL=102;RPP=6.17948;RPPR=0;RPR=120;RUN=1;SAF=118;SAP=4.92746;SAR=104;SRF=0;SRP=0;SRR=0;TYPE=snp
AB=0;ABP=0;AC=6;AF=1;AN=6;AO=225;CIGAR=1M1D3M;DP=226;DPB=180.8;DPRA=0;EPP=6.49431;EPPR=0;GTI=0;LEN=1;MEANALT=1.33333;MQM=59.7733;MQMR=0;NS=3;NUMALT=1;ODDS=89.5189;PAIRED=0.986667;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=7707;QR=0;RO=0;RPL=108;RPP=3.79203;RPPR=0;RPR=117;RUN=1;SAF=124;SAP=8.11567;SAR=101;SRF=0;SRP=0;SRR=0;TYPE=del
AB=0.515152;ABP=3.1419;AC=5;AF=0.833333;AN=6;AO=195;CIGAR=1X;DP=228;DPB=228;DPRA=0;EPP=12.3755;EPPR=8.34028;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=69.7788;PAIRED=1;PAIREDR=0.969697;PAO=0;PQA=0;PQR=0;PRO=0;QA=7079;QR=1205;RO=33;RPL=115;RPP=16.6516;RPPR=8.34028;RPR=80;RUN=1;SAF=94;SAP=3.55595;SAR=101;SRF=21;SRP=8.34028;SRR=12;TYPE=snp
AB=0.58209;ABP=6.93191;AC=1;AF=0.166667;AN=6;AO=39;CIGAR=1X;DP=220;DPB=220;DPRA=0.875817;EPP=5.73856;EPPR=5.37479;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=63.486;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1470;QR=6671;RO=180;RPL=21;RPP=3.51141;RPPR=4.21667;RPR=18;RUN=1;SAF=21;SAP=3.51141;SAR=18;SRF=88;SRP=3.20332;SRR=92;TYPE=snp
AB=0.40678;ABP=7.46366;AC=1;AF=0.166667;AN=6;AO=24;CIGAR=1M2D9M;DP=225;DPB=221;DPRA=0.710843;EPP=3.37221;EPPR=4.11819;GTI=0;LEN=2;MEANALT=2;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=81.6124;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=875;QR=7339;RO=196;RPL=10;RPP=4.45795;RPPR=26.4533;RPR=14;RUN=1;SAF=17;SAP=12.0581;SAR=7;SRF=128;SRP=42.8945;SRR=68;TYPE=del
AB=0.461538;ABP=3.84548;AC=1;AF=0.166667;AN=6;AO=30;CIGAR=1X;DP=219;DPB=219;DPRA=0.844156;EPP=26.4622;EPPR=3.42611;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=67.3506;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=1156;QR=7082;RO=188;RPL=20;RPP=10.2485;RPPR=3.0103;RPR=10;RUN=1;SAF=6;SAP=26.4622;SAR=24;SRF=69;SRP=31.8863;SRR=119;TYPE=snp
AB=0;ABP=0;AC=0;AF=0;AN=6;AO=4;CIGAR=1X;DP=193;DPB=193;DPRA=0.919118;EPP=11.6962;EPPR=4.97275;GTI=0;LEN=1;MEANALT=1.5;MQM=60;MQMR=60;NS=3;NUMALT=1;ODDS=61.3932;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=72;QR=6826;RO=187;RPL=0;RPP=11.6962;RPPR=7.20229;RPR=4;RUN=1;SAF=0;SAP=11.6962;SAR=4;SRF=101;SRP=5.62303;SRR=86;TYPE=snp
AB=0,0;ABP=0,0;AC=0,0;AF=0,0;AN=6;AO=2,3;CIGAR=1X,1X;DP=171;DPB=171;DPRA=0.571429,0.655405;EPP=7.35324,9.52472;EPPR=4.31842;GTI=0;LEN=1,1;MEANALT=2,1.5;MQM=60,60;MQMR=60;NS=3;NUMALT=2;ODDS=46.6774;PAIRED=1,1;PAIREDR=1;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=55,37;QR=5947;RO=166;RPL=1,0;RPP=3.0103,9.52472;RPPR=4.31842;RPR=1,3;RUN=1,1;SAF=1,0;SAP=3.0103,9.52472;SAR=1,3;SRF=86;SRP=3.48122;SRR=80;TYPE=snp,snp</code></pre>
</div>
</div>
<p>There’s a <em>ton</em> of INFO. Many of these are statistics you could use to filter on. The tags are all defined in the header, as we mentioned above. A couple we look at a lot are <code>DP</code>, giving the total depth, <code>AF</code> giving the alternate allele frequency, and <code>AO</code>, giving the number of reads supporting the alternate allele.</p>
<p>Now let’s look at the format and genotype fields:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:33100000-33200000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">head</span> <span class="kw">|</span> <span class="fu">cut</span> <span class="at">-f</span> 9-</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>GT:DP:AD:RO:QR:AO:QA:GL 1/1:73:0,73:0:0:73:2712:-244.24,-21.9752,0  1/1:80:0,80:0:0:80:2938:-264.561,-24.0824,0 1/1:65:0,65:0:0:65:2454:-221.045,-19.567,0
GT:DP:AD:RO:QR:AO:QA:GL 1/1:76:0,76:0:0:76:2851:-256.745,-22.8783,0 1/1:84:0,84:0:0:84:3111:-280.139,-25.2865,0 1/1:59:0,59:0:0:59:2198:-198.023,-17.7608,0
GT:DP:AD:RO:QR:AO:QA:GL 1/1:80:0,80:0:0:80:3005:-270.607,-24.0824,0 1/1:88:0,88:0:0:88:3005:-270.594,-26.4906,0 1/1:54:0,54:0:0:54:1907:-171.854,-16.2556,0
GT:DP:AD:RO:QR:AO:QA:GL 1/1:96:0,95:0:0:95:3234:-291.03,-28.5979,0  1/1:61:0,61:0:0:61:2117:-190.736,-18.3628,0 1/1:69:0,69:0:0:69:2356:-212.226,-20.7711,0
GT:DP:AD:RO:QR:AO:QA:GL 1/1:87:0,87:0:0:87:3248:-292.458,-26.1896,0 0/1:66:32,34:32:1184:34:1175:-86.148,0,-86.9768 1/1:75:1,74:1:21:74:2656:-237.119,-20.4773,0
GT:DP:AD:RO:QR:AO:QA:GL 0/0:84:83,0:83:3020:0:0:0,-24.9855,-271.782 0/0:69:69,0:69:2583:0:0:0,-20.7711,-232.64  0/1:67:28,39:28:1068:39:1470:-112.389,0,-76.2508
GT:DP:AD:RO:QR:AO:QA:GL 0/0:76:75,0:75:2831:0:0:0,-22.5772,-254.814 0/1:59:34,24:34:1257:24:875:-61.466,0,-95.8355  0/0:90:87,0:87:3251:0:0:0,-26.1896,-292.616
GT:DP:AD:RO:QR:AO:QA:GL 0/0:91:90,0:90:3378:0:0:0,-27.0927,-304.011 0/0:63:63,0:63:2374:0:0:0,-18.9649,-213.856 0/1:65:35,30:35:1330:30:1156:-84.7577,0,-100.405
GT:DP:AD:RO:QR:AO:QA:GL 0/0:72:71,1:71:2576:1:13:0,-20.3742,-230.715    0/0:53:48,3:48:1794:3:59:0,-10.1644,-156.119    0/0:68:68,0:68:2456:0:0:0,-20.47,-221.219
GT:DP:AD:RO:QR:AO:QA:GL 0/0:74:74,0,0:74:2603:0,0:0,0:0,-22.2762,-234.443,-22.2762,-234.443,-234.443    0/0:38:34,2,2:34:1226:2,2:55,25:0,-5.81527,-105.463,-8.66201,-104.431,-108.169  0/0:59:58,0,1:58:2118:0,1:0,12:0,-17.4597,-190.705,-16.5608,-189.93,-189.629</code></pre>
</div>
</div>
<p>The FORMAT field is a colon separated list of tags indicating what each genotype contains. These are also defined in the header.</p>
<p>Consider this format field <code>GT:DP:AD:RO:QR:AO:QA:GL</code> and this genotype field <code>1/1:73:0,73:0:0:73:2712:-244.24,-21.9752,0</code>. It works out like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>GT</th>
<th>DP</th>
<th>AD</th>
<th>RO</th>
<th>QR</th>
<th>AO</th>
<th>QA</th>
<th>GL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1/1</td>
<td>73</td>
<td>0,73</td>
<td>0</td>
<td>0</td>
<td>73</td>
<td>2712</td>
<td>-244.24,-21.9752,0</td>
</tr>
</tbody>
</table>
<p><code>GT</code> is the big one! Alleles are numbered from 0 as REF, ALT1, ALT2…ALTN. A genotype <code>0/1</code> indicates a REF/ALT heterozygote. The allele separator <code>/</code> indicates an unphased genotype. If the separator were instead <code>|</code> (<code>0|1</code>) that would indicate that all consecutive genotypes from that sample also using the separator were phase-known. For example, at position 1 you have <code>0|1</code>, position 10 you have <code>1|0</code> and position 20 you have <code>0|3</code>. You know that the two haplotypes spanning positions 1-20 are <code>010</code> and <code>103</code>.</p>
<p>Unphased genotypes have alleles sorted numerically, so a REF/ALT heterozygote will always be <code>0/1</code> and not <code>1/0</code>. Obviously the ordering matters for phased genotypes.</p>
<p>Missing genotypes are encoded differently by different programs. They may simply be <code>.</code> or they may be <code>./.</code>. For some programs missing genotypes will also have the rest of the annotations, but also missing, e.g <code>./.:.:.:.:.:.:.:.</code>.</p>
<p><code>DP</code> gives the total depth for the sample. <code>AD</code> is the depth for each possible allele in the genotype. We don’t often scrutinize these except in cases where we are interested in particular variants and their genotypes, or we are curious about some behavior of the variant caller that doesn’t match our expectations for the data. <code>RO</code> and <code>AO</code> give counts of REF and ALT allele observations, while <code>QR</code> and <code>QA</code>give the sums of the phred base qualities for REF and ALT alleles.</p>
<p>For most callers there will be some version of a comma-separated genotype likelihood vector, in this case <code>GL</code>, which is the log10 scaled likelihood (i.e.&nbsp;the probability of the read data) for each possible genotype given the alleles. The values are scaled so that they are relative to the highest likelihood genotype (which makes that value 0).</p>
</section>
<section id="how-do-we-dig-in-to-a-vcf-file" class="level3" data-number="4.8.3">
<h3 data-number="4.8.3" class="anchored" data-anchor-id="how-do-we-dig-in-to-a-vcf-file"><span class="header-section-number">4.8.3</span> How do we dig in to a VCF file?</h3>
<p>We’ll look at a few <em>very</em> basic things with linux/bash here, but we’ll save the bulk for the next chapter. These tricks are useful when you want a quick glance at what’s going on in a VCF file. You should only really use them on smallish regions as exploratory measures when you get results back.</p>
<p>Let’s start by asking how many variants we’ve got we’ve got in our target region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:29400000-34400000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span> <span class="fu">wc</span> <span class="at">-l</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   57423</code></pre>
</div>
</div>
<p>What do the QUAL scores look like? We’ll try four categories: &lt; 10, &gt;= 10 &amp; &lt; 30, &gt;= 30 &amp; &lt; 100, &gt;= 100.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:29400000-34400000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="st">'</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($6 &lt; 10){w+=1}}</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($6 &gt;= 10 &amp;&amp; $6 &lt; 30){x+=1}}</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($6 &gt;= 30 &amp;&amp; $6 &lt; 100){y+=1}}</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($6 &gt;= 100){z+=1}}</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="st">  END {print w,x,y,z}'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>39872 408 883 16260</code></pre>
</div>
</div>
<p>The <em>vast</em> majority are pretty very low quality. At least in this dataset, setting a QUAL threshold anywhere between 10 and 100 won’t have a big impact on the number of variants retained. GATK and bcftools won’t output so many garbage variants. Extremely high sensitivity is just how freebayes rolls.</p>
<p>We can also quickly pull out INFO field tags if we want. Let’s grab the overall depth tag <code>DP</code> and summarize it along the lines of our coverage thresholds we considered previously.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:29400000-34400000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="ex">ggrep</span> <span class="at">-oP</span> <span class="st">"(?&lt;=DP=)[0-9]+"</span> <span class="kw">|</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">awk</span> <span class="st">'</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($1 &lt; 90){w+=1}}</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($1 &gt;= 90 &amp;&amp; $1 &lt; 260){x+=1}}</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($1 &gt;= 260 &amp;&amp; $1 &lt; 1000){y+=1}}</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="st">  {if($1 &gt;= 1000){z+=1}}</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="st">  END {print w,x,y,z}'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>9748 38025 7154 2496</code></pre>
</div>
</div>
<p>Note the <code>ggrep</code> is because this is being compiled on a mac, which natively has BSD versions of <code>grep</code> with slightly different options <code>ggrep</code> is the GNU version of grep that is installed as plain old <code>grep</code> on linux systems.</p>
<p>The regex <code>"(?&lt;=DP=)[0-9]+"</code> contains a <a href="https://www.regular-expressions.info/lookaround.html">zero-length assertion</a>, it pulls out strings preceded by <code>DP=</code>.</p>
<p>There isn’t really strong concordance between the QUAL numbers and the DP numbers. Not all bad variant records fall outside the depth thresholds.</p>
<p>Let’s pull out one more tag that freebayes produces, the TYPE tag.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:29400000-34400000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="ex">ggrep</span> <span class="at">-oP</span> <span class="st">"(?&lt;=TYPE=)[a-zA-Z]+"</span> <span class="kw">|</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="at">-g</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 318 mnp
1144 ins
1416 del
3075 complex
51470 snp</code></pre>
</div>
</div>
<p>We can see the vast majority of variant records are categorized as SNPs, though we also have insertions, deletions, complex variants, and multi-nucleotide polymorphisms (typically short haployptes of just SNPs).</p>
<p>Now let’s look at the distribution of genotypes in just one sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="ex">bcftools</span> view <span class="at">-H</span> <span class="at">-r</span> chr20:29400000-34400000 variants/results/05_variantCalling/freebayes/freebayes.vcf.gz <span class="kw">|</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cut</span> <span class="at">-f</span> 10 <span class="kw">|</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="st">'s/:.*//'</span> <span class="kw">|</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span> <span class="kw">|</span> <span class="fu">uniq</span> <span class="at">-c</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="at">-g</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1 0/5
   1 0/7
   1 4/6
   3 0/4
   3 1/4
   3 2/3
   8 2/2
   9 1/3
  21 0/3
 141 .
 158 0/2
 427 1/2
2781 1/1
13722 0/1
40144 0/0</code></pre>
</div>
</div>
<p>As we might expect, most genotypes are <code>0/0</code> in this sample, with the next most common being <code>0/1</code>. We can see there are a handful of loci that have many alleles. These are probably mostly false positives. After all, with only 3 diploids, it’s impossible to have more than 6 alleles at a site, and if sites with such allelic diversity existed, it would be next to impossible to sample 6 different alleles with only three individuals anyway.</p>
</section>
</section>
<section id="conclusions" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">4.9</span> Conclusions</h2>
<p>We’ve now seen several pieces of software for calling variants from mapped data. We’ve covered the VCF format and how to dig into a little bit. In the next chapter we will look at tools for manipulating and extracting information from VCF files, summarizing them, filtering them and reformatting.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>For preprocessing, <a href="https://gatk.broadinstitute.org/hc/en-us/articles/360039568932--How-to-Map-and-clean-up-short-read-sequence-data-efficiently">they recommend</a> that fastq files be converted to <em>unmapped</em> bam so that sequences can be annotated (e.g.&nbsp;with adapter contamination), then converted back to fastq, then aligned, then finally for the aligned sequences to be merged with the unmapped bam to reintroduce the annotations made on the unmapped sequence. Whew.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02_1_qc.html" class="pagination-link" aria-label="Variant calling - First Steps">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variant calling - First Steps</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02_3_filteringVariants.html" class="pagination-link" aria-label="Filtering and Assessing Variants">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Filtering and Assessing Variants</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>