<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Assembly QC – ISG 5312 - Genomic Data Analysis in Practice II</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04_0_scRNAseq.html" rel="next">
<link href="./03_2_Assembling.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03_0_genomeAssembly.html">Genome Assembly</a></li><li class="breadcrumb-item"><a href="./03_3_assemblyQC.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Assembly QC</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ISG 5312 - Genomic Data Analysis in Practice II</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_0_IntroToGit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Git</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_1_git-ingStarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First steps with Git</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_2_moreGit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">More Git</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02_0_variantDetection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variant Detection and Genotyping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_1_qc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variant calling - First Steps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_2_variantCalling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variant Calling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_3_filteringVariants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Filtering and Assessing Variants</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_4_assessingAnnotating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Comparing and Annotating Variants</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_0_genomeAssembly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Genome Assembly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_1_genomeAssemblyKmers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Genome Assembly - first steps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_2_Assembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Assembling the genome</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_3_assemblyQC.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Assembly QC</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Single-cell RNAseq</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Pipeline development with Nextflow</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">9.1</span> Learning Objectives</a></li>
  <li><a href="#contiguity" id="toc-contiguity" class="nav-link" data-scroll-target="#contiguity"><span class="header-section-number">9.2</span> Contiguity</a></li>
  <li><a href="#completeness" id="toc-completeness" class="nav-link" data-scroll-target="#completeness"><span class="header-section-number">9.3</span> Completeness</a>
  <ul class="collapse">
  <li><a href="#busco" id="toc-busco" class="nav-link" data-scroll-target="#busco"><span class="header-section-number">9.3.1</span> BUSCO</a></li>
  <li><a href="#merqury" id="toc-merqury" class="nav-link" data-scroll-target="#merqury"><span class="header-section-number">9.3.2</span> Merqury</a></li>
  </ul></li>
  <li><a href="#correctness" id="toc-correctness" class="nav-link" data-scroll-target="#correctness"><span class="header-section-number">9.4</span> Correctness</a>
  <ul class="collapse">
  <li><a href="#merqury-1" id="toc-merqury-1" class="nav-link" data-scroll-target="#merqury-1"><span class="header-section-number">9.4.1</span> Merqury</a></li>
  <li><a href="#juicerjuicebox" id="toc-juicerjuicebox" class="nav-link" data-scroll-target="#juicerjuicebox"><span class="header-section-number">9.4.2</span> Juicer/Juicebox</a></li>
  <li><a href="#genome-comparison" id="toc-genome-comparison" class="nav-link" data-scroll-target="#genome-comparison"><span class="header-section-number">9.4.3</span> Genome comparison</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">9.5</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03_0_genomeAssembly.html">Genome Assembly</a></li><li class="breadcrumb-item"><a href="./03_3_assemblyQC.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Assembly QC</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Assembly QC</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">9.1</span> Learning Objectives</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Learning Objectives:</strong></td>
</tr>
<tr class="even">
<td>Estimate the completeness, correctness, and contiguity of an assembled genome.</td>
</tr>
</tbody>
</table>
<p>In this chapter we’ll look at some QC metrics on our assembly. We’re going to look at the three C’s</p>
<ul>
<li>Contiguity: the degree to which the assembly is fragmented.</li>
<li>Completeness: the fraction of the genome that is successfully assembled.</li>
<li>Correctness: how many errors have been incorporated into the assembly.</li>
</ul>
</section>
<section id="contiguity" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="contiguity"><span class="header-section-number">9.2</span> Contiguity</h2>
<p>In the early days of genome assembly, genomes were very highly fragmented. The fish <strong>Fundulus heteroclitus</strong> (the program mascot at this point) has a genome of around 1gb split across 24 chromosomes. In 2017, the first published genome had over 10,000 contigs, the largest of which was around 6mb. This was a very common state of affairs for genomes produced for organisms without vast research communities.</p>
<p>As we have seen, with current sequencing technologies and assembly algorithms we can regularly produce contigs on the scale of 10’s of megabases in a primary assembly, and reach chromosome-scale scaffolds with Hi-C data. But how can we compare contiguity among assemblies?</p>
<p>In those early days, the most commonly used statistic was <code>N50</code>. This is defined as <em>the contig length for which at least 50% of the genome is found in contigs that length or longer</em>. When genomes were highly fragmented, this was a somewhat useful metric both for comparing different assemblies of the same data and for communicating to others how relatively contiguous your genome was or wasn’t. Perhaps the biggest problem with it is that you could game it by tossing out tons of small scaffolds (many of which were probably real, but too small to be useful) and thereby increase your N50.</p>
<p>N50 is less useful now, because assemblies are regularly approaching chromosome-scale. The N50 number becomes very discontinuous because it’s almost certain that 50% of a newer genome will be in a contig that is 10s of megabases long, and with a chromosome-scale assembly it will be a function of the chromosome-length distribution more than anything else.</p>
<p>What is more important is information about how much of the genome remains in small contigs, many of which may fail to be scaffolded.</p>
<p>For this there are a <a href="https://en.wikipedia.org/wiki/N50,_L50,_and_related_statistics">bunch of other statistics</a>.</p>
<p>We can generalize N50 to Nx, and calculate it for any percentage of the genome. We can create an Nx plot, and <a href="https://lh3.github.io/2020/04/08/a-new-metric-on-assembly-contiguity">as proposed by Heng Li</a> we can measure the <em>area under the Nx</em> curve, <code>auN</code>.</p>
<p>If we do multiple assemblies from the same organism, these numbers can help us understand which are more contiguous. At this point they are not helpful in a universal sense because they are so dependent on the chromosome size distribution of the organism.</p>
<p>How can we calculate them? Using <a href="https://quast.sourceforge.net"><code>Quast</code></a> is an easy approach. We’ll do it here for both our unscaffolded and scaffolded haplotypes. It’s easy to do with loops because it’s not very computationally intensive. See the script <code>scripts/05_assemblyQC/01_quast.sh</code>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load quast/5.2.0</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># loop over unscaffolded assemblies</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="va">ASSEMBLIES</span><span class="op">=</span>../../results/04_assembly/hifiasm_fastas/</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_assemblyQC/quast</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> file <span class="kw">in</span> <span class="va">$(</span><span class="fu">find</span> <span class="va">${ASSEMBLIES}</span> <span class="at">-name</span> <span class="st">"*fa"</span><span class="va">)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">do</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="va">base</span><span class="op">=</span><span class="va">$(</span><span class="fu">basename</span> <span class="va">${file}</span> <span class="st">".fa"</span><span class="va">)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">echo</span> <span class="va">${base}</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span>/<span class="va">${base}</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="ex">quast.py</span> <span class="va">${file}</span> <span class="at">--threads</span> 16 <span class="at">-o</span> <span class="va">${OUTDIR}</span>/<span class="va">${base}</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="va">SCAFFOLDS</span><span class="op">=</span>../../results/04_assembly/scaffoldedAssemblies/</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># run on scaffolded haplotypes</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> file <span class="kw">in</span> <span class="va">$(</span><span class="fu">find</span> <span class="va">${SCAFFOLDS}</span> <span class="at">-name</span> <span class="st">"*fa"</span><span class="va">)</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">do</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="va">base</span><span class="op">=</span><span class="va">$(</span><span class="fu">basename</span> <span class="va">${file}</span> <span class="st">".fa"</span><span class="va">)</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">echo</span> <span class="va">${base}</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span>/<span class="va">${base}</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="ex">quast.py</span> <span class="va">${file}</span> <span class="at">--threads</span> 16 <span class="at">-o</span> <span class="va">${OUTDIR}</span>/<span class="va">${base}</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>And we get a directory for each of the five assemblies:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">ll</span> results/05_assemblyQC/quast/</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>total 20K
drwxr-xr-x 4 nreid cbc 5.5K Feb 20 19:00 Fdiaphanus_hap1
drwxr-xr-x 4 nreid cbc 5.5K Feb 20 18:58 Fdiaphanus_hap2
drwxr-xr-x 4 nreid cbc 5.5K Feb 20 19:01 Fdiaphanus_primary_contigs
drwxr-xr-x 4 nreid cbc 5.5K Feb 21 14:42 hap1_scaffolds_final
drwxr-xr-x 4 nreid cbc 5.5K Feb 21 14:44 hap2_scaffolds_final</code></pre>
<p>Within each directory we have a set of files:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">ll</span> results/05_assemblyQC/quast/Fdiaphanus_hap1/</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>total 492K
drwxr-xr-x 2 nreid cbc    0 Feb 20 18:58 basic_stats
-rw-r--r-- 1 nreid cbc  53K Feb 20 19:00 icarus.html
drwxr-xr-x 2 nreid cbc  512 Feb 20 19:00 icarus_viewers
-rw-r--r-- 1 nreid cbc 2.5K Feb 20 19:00 quast.log
-rw-r--r-- 1 nreid cbc 385K Feb 20 19:00 report.html
-rw-r--r-- 1 nreid cbc 1.3K Feb 20 18:59 report.tex
-rw-r--r-- 1 nreid cbc  562 Feb 20 18:59 report.tsv
-rw-r--r-- 1 nreid cbc 1.2K Feb 20 18:59 report.txt
-rw-r--r-- 1 nreid cbc 1.1K Feb 20 18:59 transposed_report.tex
-rw-r--r-- 1 nreid cbc  562 Feb 20 18:59 transposed_report.tsv
-rw-r--r-- 1 nreid cbc 1021 Feb 20 18:59 transposed_report.txt</code></pre>
<p>These files each contain a number of statistics, we are most interested in the <code>report*</code> files The <code>html</code> file can be opened in a browser, but to make a quick table we’re going to use a quick bash command:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span> <span class="va">$(</span><span class="fu">find</span> results/05_assemblyQC/quast/ <span class="at">-name</span> <span class="st">"report.tsv"</span> <span class="kw">|</span> <span class="fu">sort</span><span class="va">)</span> <span class="kw">|</span> <span class="fu">cut</span> <span class="at">-f</span> 1,2,4,6,8,10</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This will output a table (reformatted into markdown for readability below):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Assembly</th>
<th>Fdiaphanus_hap1</th>
<th>Fdiaphanus_hap2</th>
<th>Fdiaphanus_primary_contigs</th>
<th>hap1_scaffolds_final</th>
<th>hap2_scaffolds_final</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td># contigs (&gt;= 0 bp)</td>
<td>443</td>
<td>407</td>
<td>355</td>
<td>316</td>
<td>203</td>
</tr>
<tr class="even">
<td># contigs (&gt;= 1000 bp)</td>
<td>443</td>
<td>407</td>
<td>355</td>
<td>316</td>
<td>203</td>
</tr>
<tr class="odd">
<td># contigs (&gt;= 5000 bp)</td>
<td>443</td>
<td>407</td>
<td>355</td>
<td>315</td>
<td>203</td>
</tr>
<tr class="even">
<td># contigs (&gt;= 10000 bp)</td>
<td>443</td>
<td>407</td>
<td>355</td>
<td>315</td>
<td>203</td>
</tr>
<tr class="odd">
<td># contigs (&gt;= 25000 bp)</td>
<td>426</td>
<td>402</td>
<td>337</td>
<td>299</td>
<td>197</td>
</tr>
<tr class="even">
<td># contigs (&gt;= 50000 bp)</td>
<td>346</td>
<td>371</td>
<td>269</td>
<td>220</td>
<td>166</td>
</tr>
<tr class="odd">
<td>Total length (&gt;= 0 bp)</td>
<td>1356766612</td>
<td>1322093810</td>
<td>1360163710</td>
<td>1356787212</td>
<td>1322121710</td>
</tr>
<tr class="even">
<td>Total length (&gt;= 1000 bp)</td>
<td>1356766612</td>
<td>1322093810</td>
<td>1360163710</td>
<td>1356787212</td>
<td>1322121710</td>
</tr>
<tr class="odd">
<td>Total length (&gt;= 5000 bp)</td>
<td>1356766612</td>
<td>1322093810</td>
<td>1360163710</td>
<td>1356785212</td>
<td>1322121710</td>
</tr>
<tr class="even">
<td>Total length (&gt;= 10000 bp)</td>
<td>1356766612</td>
<td>1322093810</td>
<td>1360163710</td>
<td>1356785212</td>
<td>1322121710</td>
</tr>
<tr class="odd">
<td>Total length (&gt;= 25000 bp)</td>
<td>1356379238</td>
<td>1321982105</td>
<td>1359766148</td>
<td>1356420922</td>
<td>1321987005</td>
</tr>
<tr class="even">
<td>Total length (&gt;= 50000 bp)</td>
<td>1353457979</td>
<td>1320752580</td>
<td>1357178304</td>
<td>1353540531</td>
<td>1320754961</td>
</tr>
<tr class="odd">
<td># contigs</td>
<td>443</td>
<td>407</td>
<td>355</td>
<td>316</td>
<td>203</td>
</tr>
<tr class="even">
<td>Largest contig</td>
<td>42712095</td>
<td>35135847</td>
<td>59533521</td>
<td>65720995</td>
<td>64516896</td>
</tr>
<tr class="odd">
<td>Total length</td>
<td>1356766612</td>
<td>1322093810</td>
<td>1360163710</td>
<td>1356787212</td>
<td>1322121710</td>
</tr>
<tr class="even">
<td>GC (%)</td>
<td>41.24</td>
<td>41.20</td>
<td>41.23</td>
<td>41.24</td>
<td>41.20</td>
</tr>
<tr class="odd">
<td>N50</td>
<td>13657470</td>
<td>11733460</td>
<td>15584128</td>
<td>57079034</td>
<td>55365734</td>
</tr>
<tr class="even">
<td>N90</td>
<td>2452710</td>
<td>1933004</td>
<td>3312092</td>
<td>46132080</td>
<td>44556541</td>
</tr>
<tr class="odd">
<td>auN</td>
<td>15844887.4</td>
<td>13268193.1</td>
<td>20736238.0</td>
<td>54087839.3</td>
<td>54099759.9</td>
</tr>
<tr class="even">
<td>L50</td>
<td>31</td>
<td>36</td>
<td>24</td>
<td>12</td>
<td>12</td>
</tr>
<tr class="odd">
<td>L90</td>
<td>114</td>
<td>141</td>
<td>91</td>
<td>22</td>
<td>22</td>
</tr>
<tr class="even">
<td># N’s per 100 kbp</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>1.52</td>
<td>2.11</td>
</tr>
</tbody>
</table>
<p>We can see pretty clearly from this table that “primary_contigs” is most contiguous of the initial assemblies. This is expected, as it favors contiguity over phasing. “hap1” and “hap2” are less contiguous but still pretty good.</p>
<p>When we scaffold, however, we get huge jumps in all our stats. Note that we <em>still</em> have many scaffolds. Hap1 goes from 443 to 316 scaffolds. The N50 jumps from 13mb to 57mb. So we joined lots of large contigs. We incorporated some small contigs too, but many small ones remain unscaffolded. This is a pretty common state of affairs.</p>
<p>To be truly certain about how contiguous our genome assembly is, we’d want to have a karyotype telling us how many chromosomes there are.</p>
</section>
<section id="completeness" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="completeness"><span class="header-section-number">9.3</span> Completeness</h2>
<p>Next we’re going to ask how complete the genome is. We’ll use two approaches. One looks for genes expected to be present in the genome, and the other compares k-mers in the raw data to k-mers in the assembled genome.</p>
<section id="busco" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="busco"><span class="header-section-number">9.3.1</span> BUSCO</h3>
<p><a href="https://busco.ezlab.org"><code>BUSCO</code></a> stands for Benchmarking Universal Single Copy Orthologs. The idea is that for a given branch on the tree of life, there will be a set of genes that can reasonably be expected to occur as single-copy genes in all, or almost all of the species. When we sequence a new genome from that group, we can look for those expected single-copy genes. The state of those genes can give us a sense of our genome assembly.</p>
<ul>
<li>If we are missing lots of BUSCO genes, it suggests our assembly is probably incomplete.</li>
<li>If many BUSCO genes are fragmented, it suggests our assembly may be fragmented.</li>
<li>If many BUSCO genes are duplicated, it suggests we may have erroneously incorporated haplotigs.</li>
</ul>
<p>The genes themselves are determined through analyses of orthology across thousands of genomes that are published at <a href="https://www.orthodb.org">OrthoDB</a>, and they are collected by “lineage”. So how do we run <code>BUSCO</code>? Check out the script <code>scripts/05_assemblyQC/02_busco.sh</code>.</p>
<p>This script is an array job that loops over our initial assemblies (the scaffolded assemblies should have the same statistics).</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load busco/5.4.5</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span><span class="st">"../../results/05_assemblyQC/busco"</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="va">ASSEMBLYDIR</span><span class="op">=</span>../../results/04_assembly/hifiasm_fastas/</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="va">ASSEMBLIES</span><span class="op">=</span><span class="va">($(</span><span class="fu">find</span> <span class="va">${ASSEMBLYDIR}</span> <span class="at">-name</span> <span class="st">"*fa"</span><span class="va">))</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span><span class="va">${ASSEMBLIES</span><span class="op">[</span><span class="va">$SLURM_ARRAY_TASK_ID</span><span class="op">]</span><span class="va">}</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="va">BASE</span><span class="op">=</span><span class="va">$(</span><span class="fu">basename</span> <span class="va">${GEN}</span> <span class="st">".fa"</span><span class="va">)</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="va">DATABASE</span><span class="op">=</span><span class="st">"/isg/shared/databases/BUSCO/odb10/lineages/actinopterygii_odb10"</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="ex">busco</span> <span class="dt">\</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">-i</span> <span class="va">${GEN}</span> <span class="dt">\</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">-o</span> <span class="va">${OUTDIR}</span>/<span class="va">${BASE}</span> <span class="dt">\</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">-l</span> <span class="va">${DATABASE}</span> <span class="dt">\</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">-m</span> genome <span class="dt">\</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">-c</span> 12 <span class="dt">\</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">-f</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note that we use the actinoperygii (ray-finned fish) lineage, and that the database is present on Xanadu in a public directory. You can check that directory for more lineages, or you can output a taxonomically indented list with <code>busco --list-datasets</code>. If you want one that is not in that directory, just specify it and <code>BUSCO</code> will download it and use it. We could also have chosen the metazoa or vertebrata lineages, but these would have fewer BUSCO genes (because they are much broader taxonomic groups).</p>
<p>After running it, the main thing we’re interested in here is the short summary text file. We can print out all three of these summaries with</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">find</span> results/05_assemblyQC/busco/ <span class="at">-name</span> <span class="st">"short_summary.txt"</span> <span class="kw">|</span> <span class="fu">sort</span><span class="va">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Unfortunately the output is not in a tidy format, so it’s hard to quickly make a single table out of it as we did above.</p>
<p>For hap1:</p>
<pre><code>C:98.0%[S:96.9%,D:1.1%],F:0.7%,M:1.3%,n:3640       
3565    Complete BUSCOs (C)                        
3526    Complete and single-copy BUSCOs (S)        
39      Complete and duplicated BUSCOs (D)         
25      Fragmented BUSCOs (F)                      
50      Missing BUSCOs (M)                         
3640    Total BUSCO groups searched      </code></pre>
<p>For hap2:</p>
<pre><code>C:97.3%[S:96.3%,D:1.0%],F:0.7%,M:2.0%,n:3640       
3542    Complete BUSCOs (C)                        
3504    Complete and single-copy BUSCOs (S)        
38      Complete and duplicated BUSCOs (D)         
26      Fragmented BUSCOs (F)                      
72      Missing BUSCOs (M)                         
3640    Total BUSCO groups searched                </code></pre>
<p>For the primary assembly</p>
<pre><code>C:98.0%[S:96.8%,D:1.2%],F:0.7%,M:1.3%,n:3640       
3564    Complete BUSCOs (C)                        
3522    Complete and single-copy BUSCOs (S)        
42      Complete and duplicated BUSCOs (D)         
26      Fragmented BUSCOs (F)                      
50      Missing BUSCOs (M)                         
3640    Total BUSCO groups searched                </code></pre>
<p>We can see there are 3,640 BUSCO genes for actinopterygii. The three assemblies are virtually identical, with 97.3-98% being found, and a low duplication rate of 1-1.2%.</p>
<p>If you wanted to dig into the duplications to see if they were legitimate or reflected assembly issues, there is a table listing all the BUSCO genes and where they were found in the genome.</p>
<p>For example:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span> <span class="st">"Duplicated"</span> results/05_assemblyQC/busco/Fdiaphanus_hap1/run_actinopterygii_odb10/full_table.tsv <span class="kw">|</span> <span class="fu">head</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code># Busco id      Status  Sequence        Gene Start      Gene End        Strand  Score   Length  OrthoDB url     Description
1123at7898      Duplicated      h1tg000009l     3117127 3144839 -       3495.1  2357    https://www.orthodb.org/v10?query=1123at7898    filamin-B
1123at7898      Duplicated      h1tg000084l     1418269 1469514 -       4064.5  2267    https://www.orthodb.org/v10?query=1123at7898    filamin-B
10556at7898     Duplicated      h1tg000018l     24302395        24488546        +       1255.0  761
10556at7898     Duplicated      h1tg000060l     30584592        30607426        -       1447.0  821
11000at7898     Duplicated      h1tg000027l     14202410        14220372        -       1836.0  974     https://www.orthodb.org/v10?query=11000at7898   symplekin
11000at7898     Duplicated      h1tg000379l     35322   53281   -       1836.0  974     https://www.orthodb.org/v10?query=11000at7898   symplekin
19326at7898     Duplicated      h1tg000037l     30072669        30094293        +       1347.6  790     https://www.orthodb.org/v10?query=19326at7898   SEC24 homolog D, COPII coat complex component
19326at7898     Duplicated      h1tg000083l     11948685        11971897        -       1173.2  747     https://www.orthodb.org/v10?query=19326at7898   SEC24 homolog D, COPII coat complex component
24967at7898     Duplicated      h1tg000032l     7052149 7068031 -       797.9   514     https://www.orthodb.org/v10?query=24967at7898   Meprin A subunit
24967at7898     Duplicated      h1tg000033l     19643097        19658311        +       827.1   473     https://www.orthodb.org/v10?query=24967at7898   Meprin A subunit</code></pre>
<p>It would take a little investigating to understand these 5 duplicated genes, however.</p>
</section>
<section id="merqury" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="merqury"><span class="header-section-number">9.3.2</span> Merqury</h3>
<p>Next we’re going to run <a href="https://github.com/marbl/merqury"><code>Merqury</code></a>. <code>Merqury</code> will allow us to assess completeness by looking at the distribution of k-mers in our unassembled sequencing data compared to the ones found in the assembled genome. It will divide up the sequencing data k-mers into groups based on whether they are absent from the assembly, present in one copy, or present in more than one copy in the reference. Similarly to GenomeScope, it will fit a model to these distributions and try to estimate how many errors are found in the assembly and how much sequence data is missing.</p>
<p>To run Merqury, we first need to count the k-mers for our HiFi reads. We’ll use meryl for that. You could use the meryl k-mer count database we created before, but we’ll do it again here with script <code>scripts/05_assemblyQC/03_meryl.sh</code>. Remember meryl needs a substantial amount of memory!</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">meryl</span> count k=21 memory=200 threads=24 <span class="va">${INDIR}</span>/<span class="pp">*</span>hifi<span class="pp">*</span>fastq.gz output <span class="va">${OUTDIR}</span>/HIFI.meryl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Once we’ve got the database, we can run merqury. Check out script <code>scripts/05_assemblyQC/04_merqury.sh</code>. It’s an array script. Each task doesn’t need all that much in the way of resources. It does require R to generate some plots.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load R/4.2.2</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load merqury/1.3</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load meryl/1.4.1</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># input/output. prefix everything with $(pwd) so we can run merqury from the output directory</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="va">MERYLDIR</span><span class="op">=</span><span class="va">$(</span><span class="bu">pwd</span><span class="va">)</span>/../../results/05_assemblyQC/meryl/HIFI.meryl</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># get an assembly file</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="va">ASSEMBLYDIR</span><span class="op">=</span><span class="va">$(</span><span class="bu">pwd</span><span class="va">)</span>/../../results/04_assembly/hifiasm_fastas/</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="va">ASSEMBLIES</span><span class="op">=</span><span class="va">($(</span><span class="fu">find</span> <span class="va">${ASSEMBLYDIR}</span> <span class="at">-name</span> <span class="st">"*fa"</span><span class="va">))</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="va">GEN</span><span class="op">=</span><span class="va">${ASSEMBLIES</span><span class="op">[</span><span class="va">$SLURM_ARRAY_TASK_ID</span><span class="op">]</span><span class="va">}</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># extract file name base to use as prefix</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="va">BASE</span><span class="op">=</span><span class="va">$(</span><span class="fu">basename</span> <span class="va">${GEN}</span> <span class="st">".fa"</span><span class="va">)</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co"># run merqury from the output directory because it doesn't allow setting output location (!?!)</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_assemblyQC/merqury/<span class="va">${BASE}</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> <span class="va">${OUTDIR}</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co"># run meryl</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="ex">merqury.sh</span> <span class="va">${MERYLDIR}</span> <span class="va">${GEN}</span> <span class="va">${BASE}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>It’s a pretty simple script. It produces lots of results files. We’ll first look at the completeness stats:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">find</span> results/05_assemblyQC/merqury/ <span class="at">-name</span> <span class="st">"*completeness*"</span> <span class="kw">|</span> <span class="fu">sort</span><span class="va">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Fdiaphanus_hap1 all     872456074       880490278       99.0875
Fdiaphanus_hap2 all     867309249       880490278       98.503
Fdiaphanus_primary_contigs      all     872101987       880490278       99.0473</code></pre>
<p>Per the docs, the columns are:</p>
<ol type="1">
<li>Assembly</li>
<li>k-mer set used for measuring completeness - all = read set (This gets expended with hap-mers later)</li>
<li>solid k-mers in the assembly</li>
<li>Total solid k-mers in the read set</li>
<li>Completeness (%)</li>
</ol>
<p>“solid” k-mers are those with low frequency probable errors filtered out.</p>
<p>So this suggests our assemblies are ~99% complete, with hap2 looking a little worse. This is contingent on there being little to no bias in which parts of the genome are sequenced, so we should be aware that <a href="https://www.biorxiv.org/content/10.1101/2025.02.23.639762v1">sequencing bias can distort this</a>.</p>
<p>We also get some nice figures. The one below shows the read k-mers broken out by how frequently they occur in the assembly. You can see the spike of rare k-mers found only in the reads. Those will be errors, but also a low peak for k-mers that appear twice in the assembly. As you might expect, the peak there is about 2x the peak of the single-copy k-mers. The figure doesn’t really show higher copy number k-mers as it is truncated in the 85x range.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Fdiaphanus_hap1.Fdiaphanus_hap1.spectra-cn.fl.png" class="img-fluid figure-img"></p>
<figcaption>A k-mer frequency spectrum graph from merqury</figcaption>
</figure>
</div>
</section>
</section>
<section id="correctness" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="correctness"><span class="header-section-number">9.4</span> Correctness</h2>
<p>Our last criterion here is correctness. There are two main components here, base-level correctness and assembly level. In the first component we want to know if the actual sequences are accurate at the base level. Sequencing data with higher error rates can produce assemblies with base level errors that can benefit from polishing. In the second we want to know if whole contigs or scaffolds have been joined incorrectly. We may have the sequences themselves mostly right, but the ordering and orientation of contigs, or more rarely the initial assembly itself, may have joined sequences incorrectly.</p>
<section id="merqury-1" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="merqury-1"><span class="header-section-number">9.4.1</span> Merqury</h3>
<p><code>merqury</code> provides a relatively straightforward evaluation of base-level accuracy, again from k-mers. We’ve already run it, so we’ll just have a look at those results here. The relevant files end with suffix <code>.qv</code>. There are two for each assembly. One gives the assembly-wide average, the second gives the value for each sequence. We’ll just grab the averages (the <code>grep Fdiaph</code> does that here):</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">find</span> results/05_assemblyQC/merqury/Fdiaph<span class="pp">*</span> <span class="at">-name</span> <span class="st">"*qv"</span> <span class="kw">|</span> <span class="fu">sort</span><span class="va">)</span> <span class="kw">|</span> <span class="fu">grep</span> Fdiaph</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Fdiaphanus_hap1 20246   1356757752      61.4838 7.10593e-07
Fdiaphanus_hap2 19536   1322085670      61.5264 7.03655e-07
Fdiaphanus_primary_contigs      19284   1360156610      61.7061 6.75137e-07</code></pre>
<p>Per the docs, the columns are:</p>
<ol type="1">
<li>Assembly of interest. Both is the combination of the above two.</li>
<li>Total (present) k-mers uniquely found only in the assembly</li>
<li>Total (present) k-mers found in the assembly</li>
<li>QV (phred-scaled error rate)</li>
<li>Error rate</li>
</ol>
<p>So we can see that in our three assemblies we can expect 6-7 errors <em>per 10 million bases</em>. Not too bad!</p>
<p>Note that it is possible to provide two assemblies at once like this <code>merqury.sh ${MERYLDIR} ${GENOME1} ${GENOME2} ${BASE}</code> and it will also provide a spectrum plot reflecting that.</p>
</section>
<section id="juicerjuicebox" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="juicerjuicebox"><span class="header-section-number">9.4.2</span> Juicer/Juicebox</h3>
<p>There are a number of ways we could evaluate assembly-level accuracy. We could compare our assembly to another one from the same species that we had high confidence for. We wouldn’t be able to distinguish between structural variation and assembly errors though. We could also use a genetic map, where we use the frequency of recombination between genomic regions to figure out if we had made large-scale assembly errors. This would require a decent-sized set of offspring in a single family, or a large pedigree to do well, and it would still leave uncertainty about whether apparent errors in our focal genome were true structural variants.</p>
<p>In this section, we’ll re-use our Hi-C data to visualize a <strong>contact map</strong> on our scaffolded assembly. A contact map is a visual presentation (a heatmap) of the frequency of cross-linked DNA across the genome from our Hi-C dataset. Spoiler alert, we won’t observe any obvious assembly errors in our scaffolded assembly. This is possibly because YaHS works pretty well and we are visualizing the data it used for scaffolding.</p>
<p>There are three steps here:</p>
<ol type="1">
<li>Align the Hi-C data to the assembly. <code>YaHS</code> has already effectively done this, and it provides a script to reformat it so it can be used in the next step, rather than doing it again.</li>
<li>Run <code>juicer</code> (the <code>pre</code> module) to prepare the Hi-C alignments for visualization.</li>
<li>Visualize the data locally using <code>juicebox</code>, a GUI.</li>
</ol>
<p>There’s a lot you can do with <code>juicebox</code>, but we’re just going to get to the point of visualizing the contact map.</p>
<section id="step-1" class="level4" data-number="9.4.2.1">
<h4 data-number="9.4.2.1" class="anchored" data-anchor-id="step-1"><span class="header-section-number">9.4.2.1</span> Step 1</h4>
<p>The first step is in script <code>scripts/05_assemblyQC/05_juicerPrep.sh</code>. It’s an array set up to run once for each haplotype. The commands are taken from the <code>YaHS</code> documentation:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="va">INDIR</span><span class="op">=</span>../../results/04_assembly/scaffoldedAssemblies/</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="va">CONTIGDIR</span><span class="op">=</span>../../results/04_assembly/hifiasm_fastas/</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_assemblyQC/contactMaps</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="va">HAPS</span><span class="op">=</span><span class="va">(</span>1 2<span class="va">)</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="va">hap</span><span class="op">=</span><span class="va">${HAPS</span><span class="op">[</span><span class="va">$SLURM_ARRAY_TASK_ID</span><span class="op">]</span><span class="va">}</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># convert bin file created by yahs</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># "juicer pre" is a script provided by yahs</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="va">BIN</span><span class="op">=</span><span class="va">${INDIR}</span>/hap<span class="va">${hap}</span>.bin</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="va">AGP</span><span class="op">=</span><span class="va">${INDIR}</span>/hap<span class="va">${hap}</span>_scaffolds_final.agp</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="va">FAI</span><span class="op">=</span><span class="va">${CONTIGDIR}</span>/Fdiaphanus_hap<span class="va">${hap}</span>.fa.fai</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="ex">juicer</span> pre <span class="va">${BIN}</span> <span class="va">${AGP}</span> <span class="va">${FAI}</span> <span class="kw">|</span> </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sort</span> <span class="at">-k2,2d</span> <span class="at">-k6,6d</span> <span class="at">-T</span> ./ <span class="at">--parallel</span><span class="op">=</span>8 <span class="at">-S32G</span> <span class="kw">|</span> </span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">awk</span> <span class="st">'NF'</span> <span class="op">&gt;</span> <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_alignments_sorted.txt.part<span class="kw">)</span> <span class="kw">&amp;&amp;</span> </span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="fu">mv</span> <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_alignments_sorted.txt.part <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_alignments_sorted.txt<span class="kw">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>.bin</code> file contains the Hi-C mapping information created by <code>YaHS</code>. It’s mapped to the <em>contigs</em> in our assemblies, but we want to visualize the <em>scaffolds</em>, so it needs to be converted. The <code>.agp</code> file from <code>YaHS</code> contains the information needed to translate from the contig coordinates to the scaffold coordinates. The <code>.fai</code> file just contains the scaffold names and lengths.</p>
<p>Confusingly the command <code>juicer pre</code> is provided by YaHS, but shares the same name and submodule name as the java program we’ll run in the next step. Then next two lines sort by columns 2 and 6 and remove any empty lines.</p>
</section>
<section id="step-2" class="level4" data-number="9.4.2.2">
<h4 data-number="9.4.2.2" class="anchored" data-anchor-id="step-2"><span class="header-section-number">9.4.2.2</span> Step 2</h4>
<p>The next step formats the data so that it can be loaded up into <code>juicebox</code> and visualized. The script is <code>scripts/05_assemblyQC/06_juicerMap.sh</code>.</p>
<p>The script looks like this (as recommended by the YaHs docs):</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load YaHS/1.2.2</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load juicer/1.22.01 <span class="co"># sets $JUICER variable</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load samtools/1.20</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="va">SCAFFOLDS</span><span class="op">=</span>../../results/04_assembly/scaffoldedAssemblies/</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_assemblyQC/contactMaps</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="va">HAPS</span><span class="op">=</span><span class="va">(</span>1 2<span class="va">)</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="va">hap</span><span class="op">=</span><span class="va">${HAPS</span><span class="op">[</span><span class="va">$SLURM_ARRAY_TASK_ID</span><span class="op">]</span><span class="va">}</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># generate "chrom.sizes" file</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> faidx <span class="va">${SCAFFOLDS}</span>/hap<span class="va">${hap}</span>_scaffolds_final.fa</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="va">FAI</span><span class="op">=</span><span class="va">${SCAFFOLDS}</span>/hap<span class="va">${hap}</span>_scaffolds_final.fa.fai</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cut</span> <span class="at">-f</span> 1-2 <span class="va">${FAI}</span> <span class="op">&gt;</span><span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_scaffolds_final.chrom.sizes</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co"># run juicer to produce .hic file</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="ex">java</span> <span class="at">-jar</span> <span class="at">-Xmx32G</span> <span class="va">${JUICER}</span> pre <span class="at">--threads</span> 12 <span class="dt">\</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_alignments_sorted.txt <span class="dt">\</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_out.hic.part <span class="dt">\</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_scaffolds_final.chrom.sizes<span class="kw">)</span> <span class="kw">&amp;&amp;</span> </span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="kw">(</span><span class="fu">mv</span> <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_out.hic.part <span class="va">${OUTDIR}</span>/hap<span class="va">${hap}</span>_out.hic<span class="kw">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>There are a couple things happening here. First, we need a <code>chrom.sizes</code> file (the first two columns of a <code>.fai</code> file) for our scaffolded assembly. So we use samtools to generate the <code>.fai</code> index, and then pull out the first two columns.</p>
<p>Next, we run <code>juicer</code>, a java program. <code>${OUTDIR}/hap${hap}_alignments_sorted.txt</code> is the input generated in the last step. <code>${OUTDIR}/hap${hap}_out.hic.part</code> is the name of the output file. then we provide the <code>chrom.sizes</code> file. At the end the output file is renamed.</p>
<p><code>${OUTDIR}/hap${hap}_out.hic</code> is what we’ll load into <code>juicebox</code>.</p>
</section>
<section id="step-3" class="level4" data-number="9.4.2.3">
<h4 data-number="9.4.2.3" class="anchored" data-anchor-id="step-3"><span class="header-section-number">9.4.2.3</span> Step 3</h4>
<p>Now we need to load the <code>.hic</code> file into <code>juicebox</code>. To do this I recommend you follow the <code>Quick Start</code> instructions <a href="https://github.com/aidenlab/Juicebox/wiki">here</a>. To actually load the .hic file, you should either download it (it’s 2GB for this genome) or connect your file system to Xanadu to access it. It loads relatively quickly from Xanadu. When you do <code>File -&gt; Open</code>, select <code>Local...</code> to access your file system (or Xanadu’s if it’s connected).</p>
<p>Once you’ve got it loaded up, you can zoom in and have a look at specific scaffolds, or export figures like this.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2025.03.06.19.19.12.HiCImage.jpg" class="img-fluid figure-img"></p>
<figcaption>A Hi-C contact map</figcaption>
</figure>
</div>
<p>There are lots of things you can do with juicebox, including <a href="https://github.com/aidenlab/Juicebox/wiki/Juicebox-Assembly-Tools">editing your assembly</a>.</p>
</section>
</section>
<section id="genome-comparison" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="genome-comparison"><span class="header-section-number">9.4.3</span> Genome comparison</h3>
<p>The last thing we’ll do here is visualize a pairwise genome alignment. We’ll generate a dotplot showing the broad-scale alignment of <em>Fundulus diaphanus</em> and <em>Fundulus heteroclitus</em>. There are tons of ways to align whole genomes and analyze or visualize results. We’ll demo a pretty simple one here that is suitable for quick exploratory work.</p>
<p>We’re going to use the package <a href="https://mummer4.github.io/tutorial/tutorial.html"><code>MUMmer</code></a> to do the whole genome alignment, and a git repository called <code>Dot</code> to do an interactive visualization of a dot plot.</p>
<p>See script <code>scripts/05_assemblyQC/07_mummer.sh</code>.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="ex">module</span> load MUMmer/4.0.2</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># in/out dirs</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_assemblyQC/nucmer</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> <span class="va">${OUTDIR}</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fdiaph genome</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="va">FDIAPH</span><span class="op">=</span>../../results/04_assembly/scaffoldedAssemblies/hap1_scaffolds_final.fa</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># download Fhet genome</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">wget</span> <span class="at">-P</span> <span class="va">${OUTDIR}</span> https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/011/125/445/GCF_011125445.2_MU-UCD_Fhet_4.1/GCF_011125445.2_MU-UCD_Fhet_4.1_genomic.fna.gz</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="fu">gunzip</span> <span class="va">${OUTDIR}</span>/GCF_011125445.2_MU-UCD_Fhet_4.1_genomic.fna.gz</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="va">FHET</span><span class="op">=</span><span class="va">${OUTDIR}</span>/GCF_011125445.2_MU-UCD_Fhet_4.1_genomic.fna</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># run nucmer to generate the alignment</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="ex">nucmer</span> <span class="at">--delta</span><span class="op">=</span><span class="st">"</span><span class="va">${OUTDIR}</span><span class="st">"</span> <span class="at">-t</span> 16 <span class="va">${FDIAPH}</span> <span class="va">${FHET}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We’re running the script <code>nucmer</code> here (which wraps some <code>MUMmer</code> functions). It’s very simple. The main output file will be called <code>out.delta</code> by default.</p>
<p>Next we’ll post-process the output for <code>Dot</code> using script <code>scripts/05_assemblyQC/08_dot.sh</code>.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># in/out dirs</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span>../../results/05_assemblyQC/nucmer</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> <span class="va">${OUTDIR}</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># clone Dot repository</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/MariaNattestad/dot.git</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># remove shebang line (it points to system python)</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="at">-i</span> <span class="st">'1d'</span> dot/DotPrep.py</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># prep data for display:</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> dot/DotPrep.py <span class="at">--delta</span> out.delta <span class="at">--out</span> dotplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If this errors out for you, you may need to <code>pip install</code> <code>numpy</code> or use a conda environment with that python package installed.</p>
<p>this will produce the files:</p>
<pre><code>-rw-r--r-- 1 nreid cbc 145M Mar  1 09:26 dotplot.coords
-rw-r--r-- 1 nreid cbc 353K Mar  1 09:26 dotplot.coords.idx
-rw-r--r-- 1 nreid cbc  13M Mar  1 09:26 dotplot.uniqueAnchorFiltered_l10000.delta.gz</code></pre>
<p>We can then load those into a webserver at <a href="https://dot.sandbox.bio/">https://dot.sandbox.bio/</a>. The files are not that big, so you can download them. Alternatively you can connect Xanadu to your local filesystem to access them directly.</p>
<p>You can click and drag to create a window to zoom into, or double-click to zoom out. You can see that the overall structure of the chromosomes is pretty well preserved. The Fhet genome was assembled with high error rate PacBio CLR data, so it is not quite as good as our Fdiaph genome.</p>
<p>One interesting feature is the Fhet sequence <code>NC_046364.1</code>. You should be able to see that it is the least colinear chromosome.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/dotplot.jpg" class="img-fluid figure-img"></p>
<figcaption>NC_046364.1</figcaption>
</figure>
</div>
<p>It so happens that this is the sex chromosome in Fhet (this is unpublished data). In that species, the sex chromosomes are XY, but are not highly degenerate. This means the X and Y still share most sequence. There is, however, a very large region where they do not recombine, and that region has accumulated lots of sequence divergence between X and Y. It looks like there has probably also been lots of inversion activity. The individual Fhet used in this assembly is a male, and at least some of this sequence is Y chromosomal, but with CLR data it’s very hard to do a phased assembly, so it’s not really clear how much of this chromosome is X and how much is Y. It’s probably a mixture. Fdiaph almost certainly has genetic sex determination, but there hasn’t been any work yet trying to uncover sex chromosomes.</p>
</section>
</section>
<section id="conclusion" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">9.5</span> Conclusion</h2>
<p>This concludes our module on genome assembly. We’ve covered the most important steps in QC’ing our data, assembling the genome, and QC’ing the assembly. Remember that data and methods in this area are changing very rapidly right now, so don’t treat this material as fixed, but as more of a conceptual guide for how to approach this topic.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_2_Assembling.html" class="pagination-link" aria-label="Assembling the genome">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Assembling the genome</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04_0_scRNAseq.html" class="pagination-link" aria-label="Single-cell RNAseq">
        <span class="nav-page-text">Single-cell RNAseq</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>