project:
  type: book

book:
  title: "ISG 5312 - Genomic Data Analysis in Practice II"
  author: "Noah Reid"
  date: "11/1/2024"
  chapters:
  - index.qmd
  - part: 01_0_IntroToGit.qmd
    chapters:
    - 01_1_git-ingStarted.qmd
    - 01_2_moreGit.qmd
  - part: 02_0_variantDetection.qmd
    chapters:
    - 02_1_qc.qmd
    - 02_2_variantCalling.qmd
    - 02_3_filteringVariants.qmd
    - 02_4_assessingAnnotating.qmd
  - part: 03_0_genomeAssembly.qmd
    chapters:
    - 03_1_genomeAssemblyKmers.qmd
    - 03_2_Assembling.qmd
    # - 03_3_assemblyQC.qmd
  - part: 04_0_scRNAseq.qmd
    # chapters:
    # - 04_1.qmd
    # - 04_2.qmd
    # - 04_3.qmd
    # - 04_4.qmd
    # - 04_5.qmd
  - part: 05_0_workflows.qmd
    # chapters:
    # - 04_1.qmd
    # - 04_2.qmd
    # - 04_3.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




